// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(DISTINCT (harness || '|' || session_id))::bigint
FROM work_events
WHERE tenant = $1
  AND kind IN ('session.start', 'session.heartbeat', 'session.end')
`

// Counts distinct (harness, session_id) pairs that have at least one
// session lifecycle event for a given tenant.
func (q *Queries) CountSessions(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions, tenant)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestHeartbeat = `-- name: GetLatestHeartbeat :one
SELECT received_at
FROM work_events
WHERE harness = $1
  AND session_id = $2
  AND tenant = $3
  AND kind IN ('session.start', 'session.heartbeat')
ORDER BY received_at DESC
LIMIT 1
`

type GetLatestHeartbeatParams struct {
	Harness   string `json:"harness"`
	SessionID string `json:"session_id"`
	Tenant    string `json:"tenant"`
}

// Returns the latest session.start or session.heartbeat received_at for a
// supervised (harness, session_id, tenant). Used to compute supervised liveness.
// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
// Returns pgx.ErrNoRows if no start/heartbeat exists.
func (q *Queries) GetLatestHeartbeat(ctx context.Context, arg GetLatestHeartbeatParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestHeartbeat, arg.Harness, arg.SessionID, arg.Tenant)
	var received_at pgtype.Timestamptz
	err := row.Scan(&received_at)
	return received_at, err
}

const getSessionStartTime = `-- name: GetSessionStartTime :one
SELECT received_at
FROM work_events
WHERE harness = $1
  AND session_id = $2
  AND tenant = $3
  AND kind = 'session.start'
ORDER BY received_at ASC
LIMIT 1
`

type GetSessionStartTimeParams struct {
	Harness   string `json:"harness"`
	SessionID string `json:"session_id"`
	Tenant    string `json:"tenant"`
}

// Returns the received_at of the first session.start event for a session.
// Used to compute bounded_max_age (6h backstop from contract §4).
// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
// Returns pgx.ErrNoRows if no session.start exists.
func (q *Queries) GetSessionStartTime(ctx context.Context, arg GetSessionStartTimeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSessionStartTime, arg.Harness, arg.SessionID, arg.Tenant)
	var received_at pgtype.Timestamptz
	err := row.Scan(&received_at)
	return received_at, err
}

const getSessionTerminalEvent = `-- name: GetSessionTerminalEvent :one
SELECT id, harness, session_id, kind, status, received_at
FROM work_events
WHERE harness = $1
  AND session_id = $2
  AND tenant = $3
  AND kind = 'session.end'
ORDER BY received_at DESC
LIMIT 1
`

type GetSessionTerminalEventParams struct {
	Harness   string `json:"harness"`
	SessionID string `json:"session_id"`
	Tenant    string `json:"tenant"`
}

type GetSessionTerminalEventRow struct {
	ID         pgtype.UUID        `json:"id"`
	Harness    string             `json:"harness"`
	SessionID  string             `json:"session_id"`
	Kind       string             `json:"kind"`
	Status     pgtype.Text        `json:"status"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

// Returns the latest session.end event for a (harness, session_id, tenant), if any.
// Used to check if a session is in a terminal (absorbing) state.
// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
// Returns pgx.ErrNoRows if no terminal event exists.
func (q *Queries) GetSessionTerminalEvent(ctx context.Context, arg GetSessionTerminalEventParams) (GetSessionTerminalEventRow, error) {
	row := q.db.QueryRow(ctx, getSessionTerminalEvent, arg.Harness, arg.SessionID, arg.Tenant)
	var i GetSessionTerminalEventRow
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.SessionID,
		&i.Kind,
		&i.Status,
		&i.ReceivedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many

SELECT DISTINCT ON (harness, session_id)
    harness,
    session_id,
    host,
    pid,
    liveness_mode,
    tenant,
    kind,
    status,
    received_at,
    ts
FROM work_events
WHERE tenant = $1
  AND kind IN ('session.start', 'session.heartbeat', 'session.end')
ORDER BY harness, session_id, received_at DESC
`

type ListActiveSessionsRow struct {
	Harness      string             `json:"harness"`
	SessionID    string             `json:"session_id"`
	Host         string             `json:"host"`
	Pid          pgtype.Int4        `json:"pid"`
	LivenessMode pgtype.Text        `json:"liveness_mode"`
	Tenant       string             `json:"tenant"`
	Kind         string             `json:"kind"`
	Status       pgtype.Text        `json:"status"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	Ts           pgtype.Timestamptz `json:"ts"`
}

// Agent session liveness queries for the fleet monitor (WP-J, F10).
// NOTE: The SessionLivenessService (session_liveness.go) uses inline raw SQL
// rather than these sqlc-generated queries. This file exists as the declared
// contract for the liveness queries. If the service SQL drifts from these
// declarations, the tests in session_liveness_test.go will catch it. A future
// refactor may wire these generated queries directly.
// Returns all sessions for a tenant that have a session.start event, ordered by
// the latest event received_at descending. The caller derives liveness from
// the returned events in application code (contract §4: pure function of events + clock).
// Tenant is required (never empty — ADR-002).
func (q *Queries) ListActiveSessions(ctx context.Context, tenant string) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsRow
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.Pid,
			&i.LivenessMode,
			&i.Tenant,
			&i.Kind,
			&i.Status,
			&i.ReceivedAt,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
