// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_mail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMailbox = `-- name: CountMailbox :one
SELECT COUNT(*) FROM agent_mail
WHERE recipient_id = $1
  AND status <> 'expired'
  AND ($2::mail_status IS NULL OR status = $2)
  AND ($3::mail_priority IS NULL OR priority = $3)
  AND ($4::timestamptz IS NULL OR created_at > $4)
  AND (expires_at IS NULL OR expires_at > NOW())
`

type CountMailboxParams struct {
	RecipientID pgtype.UUID        `json:"recipient_id"`
	Status      NullMailStatus     `json:"status"`
	Priority    NullMailPriority   `json:"priority"`
	Since       pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountMailbox(ctx context.Context, arg CountMailboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMailbox,
		arg.RecipientID,
		arg.Status,
		arg.Priority,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*) FROM agent_mail
WHERE recipient_id = $1
  AND status IN ('queued', 'delivered')
  AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountUnread(ctx context.Context, recipientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireMail = `-- name: ExpireMail :exec
UPDATE agent_mail
SET status = 'expired'
WHERE status IN ('queued', 'delivered')
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
`

func (q *Queries) ExpireMail(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireMail)
	return err
}

const expireMailByID = `-- name: ExpireMailByID :one
UPDATE agent_mail
SET status = 'expired'
WHERE id = $1
  AND recipient_id = $2
RETURNING id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at
`

type ExpireMailByIDParams struct {
	ID          int64       `json:"id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) ExpireMailByID(ctx context.Context, arg ExpireMailByIDParams) (AgentMail, error) {
	row := q.db.QueryRow(ctx, expireMailByID, arg.ID, arg.RecipientID)
	var i AgentMail
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Subject,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.ReplyToID,
		&i.Metadata,
		&i.ContentType,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMail = `-- name: GetMail :one
SELECT id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at FROM agent_mail
WHERE id = $1
  AND recipient_id = $2
`

type GetMailParams struct {
	ID          int64       `json:"id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) GetMail(ctx context.Context, arg GetMailParams) (AgentMail, error) {
	row := q.db.QueryRow(ctx, getMail, arg.ID, arg.RecipientID)
	var i AgentMail
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Subject,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.ReplyToID,
		&i.Metadata,
		&i.ContentType,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMailThread = `-- name: GetMailThread :many
SELECT id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at FROM agent_mail
WHERE recipient_id = $1
  AND (id = $2 OR reply_to_id = $2)
ORDER BY created_at ASC
`

type GetMailThreadParams struct {
	RecipientID pgtype.UUID `json:"recipient_id"`
	RootID      int64       `json:"root_id"`
}

func (q *Queries) GetMailThread(ctx context.Context, arg GetMailThreadParams) ([]AgentMail, error) {
	rows, err := q.db.Query(ctx, getMailThread, arg.RecipientID, arg.RootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMail
	for rows.Next() {
		var i AgentMail
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Subject,
			&i.Body,
			&i.Priority,
			&i.Status,
			&i.ReplyToID,
			&i.Metadata,
			&i.ContentType,
			&i.ExpiresAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailbox = `-- name: GetMailbox :many
SELECT id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at FROM agent_mail
WHERE recipient_id = $1
  AND status <> 'expired'
  AND ($2::mail_status IS NULL OR status = $2)
  AND ($3::mail_priority IS NULL OR priority = $3)
  AND ($4::timestamptz IS NULL OR created_at > $4)
  -- Exclude time-expired mail from the inbox regardless of status, so a
  -- message whose expires_at has passed never surfaces.
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY priority DESC, created_at DESC
LIMIT $6 OFFSET $5
`

type GetMailboxParams struct {
	RecipientID pgtype.UUID        `json:"recipient_id"`
	Status      NullMailStatus     `json:"status"`
	Priority    NullMailPriority   `json:"priority"`
	Since       pgtype.Timestamptz `json:"since"`
	SkipRows    int32              `json:"skip_rows"`
	MaxRows     int32              `json:"max_rows"`
}

func (q *Queries) GetMailbox(ctx context.Context, arg GetMailboxParams) ([]AgentMail, error) {
	rows, err := q.db.Query(ctx, getMailbox,
		arg.RecipientID,
		arg.Status,
		arg.Priority,
		arg.Since,
		arg.SkipRows,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMail
	for rows.Next() {
		var i AgentMail
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Subject,
			&i.Body,
			&i.Priority,
			&i.Status,
			&i.ReplyToID,
			&i.Metadata,
			&i.ContentType,
			&i.ExpiresAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailRead = `-- name: MarkMailRead :one
UPDATE agent_mail
SET status = 'read', read_at = NOW()
WHERE id = $1
  AND recipient_id = $2
  AND status IN ('queued', 'delivered')
RETURNING id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at
`

type MarkMailReadParams struct {
	ID          int64       `json:"id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) MarkMailRead(ctx context.Context, arg MarkMailReadParams) (AgentMail, error) {
	row := q.db.QueryRow(ctx, markMailRead, arg.ID, arg.RecipientID)
	var i AgentMail
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Subject,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.ReplyToID,
		&i.Metadata,
		&i.ContentType,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const sendMail = `-- name: SendMail :one

INSERT INTO agent_mail (
    sender_id, recipient_id, subject, body, priority, status,
    reply_to_id, metadata, content_type, expires_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
RETURNING id, sender_id, recipient_id, subject, body, priority, status, reply_to_id, metadata, content_type, expires_at, read_at, created_at
`

type SendMailParams struct {
	SenderID    pgtype.UUID        `json:"sender_id"`
	RecipientID pgtype.UUID        `json:"recipient_id"`
	Subject     string             `json:"subject"`
	Body        string             `json:"body"`
	Priority    MailPriority       `json:"priority"`
	Status      MailStatus         `json:"status"`
	ReplyToID   pgtype.Int8        `json:"reply_to_id"`
	Metadata    []byte             `json:"metadata"`
	ContentType string             `json:"content_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// agent_mail.sql — agent-to-agent messaging (WP-101, issue #112).
// All inbox reads are scoped by recipient_id (an agent only ever sees its own
// mail). Expired mail (expires_at in the past) is excluded from inbox listings
// and unread counts so the absence is observable without a background sweeper.
func (q *Queries) SendMail(ctx context.Context, arg SendMailParams) (AgentMail, error) {
	row := q.db.QueryRow(ctx, sendMail,
		arg.SenderID,
		arg.RecipientID,
		arg.Subject,
		arg.Body,
		arg.Priority,
		arg.Status,
		arg.ReplyToID,
		arg.Metadata,
		arg.ContentType,
		arg.ExpiresAt,
	)
	var i AgentMail
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Subject,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.ReplyToID,
		&i.Metadata,
		&i.ContentType,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
