// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, display_name, harness, base_url, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at
`

type CreateAgentParams struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Harness     string `json:"harness"`
	BaseUrl     string `json:"base_url"`
	Metadata    []byte `json:"metadata"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.DisplayName,
		arg.Harness,
		arg.BaseUrl,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at FROM agents WHERE name = $1
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at FROM agents ORDER BY created_at
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Harness,
			&i.BaseUrl,
			&i.Status,
			&i.Metadata,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET display_name = $2, harness = $3, base_url = $4, metadata = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at
`

type UpdateAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Harness     string      `json:"harness"`
	BaseUrl     string      `json:"base_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.DisplayName,
		arg.Harness,
		arg.BaseUrl,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents SET status = $2, last_seen = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at
`

type UpdateAgentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus, arg.ID, arg.Status)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
