// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (owner_id, name, display_name, harness, base_url, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type CreateAgentParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	Harness     string      `json:"harness"`
	BaseUrl     string      `json:"base_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OwnerID,
		arg.Name,
		arg.DisplayName,
		arg.Harness,
		arg.BaseUrl,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1 AND owner_id = $2
`

type DeleteAgentParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) error {
	_, err := q.db.Exec(ctx, deleteAgent, arg.ID, arg.OwnerID)
	return err
}

const ensureAgent = `-- name: EnsureAgent :one
INSERT INTO agents (owner_id, name, display_name, harness, base_url, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type EnsureAgentParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	Harness     string      `json:"harness"`
	BaseUrl     string      `json:"base_url"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) EnsureAgent(ctx context.Context, arg EnsureAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, ensureAgent,
		arg.OwnerID,
		arg.Name,
		arg.DisplayName,
		arg.Harness,
		arg.BaseUrl,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents WHERE id = $1 AND owner_id = $2
`

type GetAgentParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.OwnerID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents WHERE name = $1 AND owner_id = $2
`

type GetAgentByNameParams struct {
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByName, arg.Name, arg.OwnerID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const getAgentByNameAndOwner = `-- name: GetAgentByNameAndOwner :one
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents WHERE name = $1 AND owner_id = $2
`

type GetAgentByNameAndOwnerParams struct {
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetAgentByNameAndOwner(ctx context.Context, arg GetAgentByNameAndOwnerParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByNameAndOwner, arg.Name, arg.OwnerID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents WHERE owner_id = $1 ORDER BY created_at
`

func (q *Queries) ListAgents(ctx context.Context, ownerID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Harness,
			&i.BaseUrl,
			&i.Status,
			&i.Metadata,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.SystemPrompt,
			&i.Persona,
			&i.Visible,
			&i.OwnerID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByProject = `-- name: ListAgentsByProject :many
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents
WHERE owner_id = $1 AND project_id = $2 AND visible = true
ORDER BY created_at
`

type ListAgentsByProjectParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// Workspace scoping (issue #134): agents assigned to a given project.
func (q *Queries) ListAgentsByProject(ctx context.Context, arg ListAgentsByProjectParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProject, arg.OwnerID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Harness,
			&i.BaseUrl,
			&i.Status,
			&i.Metadata,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.SystemPrompt,
			&i.Persona,
			&i.Visible,
			&i.OwnerID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAgents = `-- name: ListVisibleAgents :many
SELECT id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id FROM agents WHERE owner_id = $1 AND visible = true ORDER BY created_at
`

func (q *Queries) ListVisibleAgents(ctx context.Context, ownerID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listVisibleAgents, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Harness,
			&i.BaseUrl,
			&i.Status,
			&i.Metadata,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.SystemPrompt,
			&i.Persona,
			&i.Visible,
			&i.OwnerID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAgent = `-- name: RenameAgent :one
UPDATE agents SET name = $2, display_name = $3, updated_at = NOW()
WHERE id = $1 AND owner_id = $4
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type RenameAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) RenameAgent(ctx context.Context, arg RenameAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, renameAgent,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.OwnerID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const setAgentProject = `-- name: SetAgentProject :one
UPDATE agents SET project_id = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type SetAgentProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

// Assign (or clear, when project_id is NULL) an agent to a workspace.
func (q *Queries) SetAgentProject(ctx context.Context, arg SetAgentProjectParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentProject, arg.ID, arg.ProjectID, arg.OwnerID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET display_name = $2, harness = $3, base_url = $4, metadata = $5, updated_at = NOW()
WHERE id = $1 AND owner_id = $6
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type UpdateAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Harness     string      `json:"harness"`
	BaseUrl     string      `json:"base_url"`
	Metadata    []byte      `json:"metadata"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.DisplayName,
		arg.Harness,
		arg.BaseUrl,
		arg.Metadata,
		arg.OwnerID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const updateAgentConfig = `-- name: UpdateAgentConfig :one
UPDATE agents SET role = $2, system_prompt = $3, persona = $4, updated_at = NOW()
WHERE id = $1 AND owner_id = $5
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type UpdateAgentConfigParams struct {
	ID           pgtype.UUID `json:"id"`
	Role         pgtype.Text `json:"role"`
	SystemPrompt pgtype.Text `json:"system_prompt"`
	Persona      []byte      `json:"persona"`
	OwnerID      pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentConfig,
		arg.ID,
		arg.Role,
		arg.SystemPrompt,
		arg.Persona,
		arg.OwnerID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents SET status = $2, last_seen = NOW(), updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, name, display_name, harness, base_url, status, metadata, last_seen, created_at, updated_at, role, system_prompt, persona, visible, owner_id, project_id
`

type UpdateAgentStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus, arg.ID, arg.Status, arg.OwnerID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Harness,
		&i.BaseUrl,
		&i.Status,
		&i.Metadata,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.SystemPrompt,
		&i.Persona,
		&i.Visible,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}
