// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package db

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM app_settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, is_secret, enc_value, last4, updated_at
FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.EncValue,
		&i.Last4,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, is_secret, enc_value, last4, updated_at
FROM app_settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.EncValue,
			&i.Last4,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO app_settings (key, value, is_secret, enc_value, last4, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (key) DO UPDATE
  SET value = EXCLUDED.value,
      is_secret = EXCLUDED.is_secret,
      enc_value = EXCLUDED.enc_value,
      last4 = EXCLUDED.last4,
      updated_at = NOW()
RETURNING key, value, is_secret, enc_value, last4, updated_at
`

type UpsertSettingParams struct {
	Key      string `json:"key"`
	Value    string `json:"value"`
	IsSecret bool   `json:"is_secret"`
	EncValue []byte `json:"enc_value"`
	Last4    string `json:"last4"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.EncValue,
		arg.Last4,
	)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.EncValue,
		&i.Last4,
		&i.UpdatedAt,
	)
	return i, err
}
