// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtifacts = `-- name: CountArtifacts :one
SELECT COUNT(*) FROM artifacts WHERE ($1::text IS NULL OR type = $1)
`

func (q *Queries) CountArtifacts(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifacts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (agent_id, type, title, description, file_path, mime_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, type, title, description, file_path, mime_type, metadata, created_at
`

type CreateArtifactParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Type        string      `json:"type"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	FilePath    pgtype.Text `json:"file_path"`
	MimeType    pgtype.Text `json:"mime_type"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.AgentID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.FilePath,
		arg.MimeType,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, agent_id, type, title, description, file_path, mime_type, metadata, created_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.FilePath,
		&i.MimeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, agent_id, type, title, description, file_path, mime_type, metadata, created_at FROM artifacts
WHERE ($1::text IS NULL OR type = $1)
  AND ($2::uuid IS NULL OR agent_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListArtifactsParams struct {
	Column1 string      `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.FilePath,
			&i.MimeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
