// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (owner_id, agent_id, title, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type CreateConversationParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
	Title    pgtype.Text `json:"title"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.OwnerID,
		arg.AgentID,
		arg.Title,
		arg.Metadata,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (owner_id, conversation_id, role, content, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, role, content, metadata, created_at, owner_id
`

type CreateMessageParams struct {
	OwnerID        pgtype.UUID `json:"owner_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.OwnerID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1 AND owner_id = $2
`

type DeleteConversationParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.OwnerID)
	return err
}

const deleteLastExchange = `-- name: DeleteLastExchange :execrows
WITH last_user AS (
    SELECT id FROM messages
    WHERE messages.conversation_id = $1 AND messages.owner_id = $2 AND messages.role = 'user'
    ORDER BY messages.created_at DESC LIMIT 1
),
last_assistant AS (
    SELECT id FROM messages
    WHERE messages.conversation_id = $1 AND messages.owner_id = $2 AND messages.role = 'assistant'
    ORDER BY messages.created_at DESC LIMIT 1
)
DELETE FROM messages WHERE id IN (SELECT id FROM last_user) OR id IN (SELECT id FROM last_assistant)
`

type DeleteLastExchangeParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteLastExchange(ctx context.Context, arg DeleteLastExchangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLastExchange, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1 AND owner_id = $2
`

type DeleteMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.OwnerID)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :execrows
DELETE FROM messages WHERE conversation_id = $1 AND owner_id = $2
`

type DeleteMessagesByConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, arg DeleteMessagesByConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesByConversation, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one
SELECT id, agent_id, title, metadata, created_at, updated_at, summary, owner_id FROM conversations WHERE id = $1 AND owner_id = $2
`

type GetConversationParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const getLastUserMessage = `-- name: GetLastUserMessage :one
SELECT m.id, m.conversation_id, m.role, m.content, m.metadata, m.created_at, m.owner_id FROM messages m
JOIN conversations c ON m.conversation_id = c.id
WHERE m.conversation_id = $1 AND c.owner_id = $2 AND m.role = 'user'
ORDER BY m.created_at DESC LIMIT 1
`

type GetLastUserMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetLastUserMessage(ctx context.Context, arg GetLastUserMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getLastUserMessage, arg.ConversationID, arg.OwnerID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.agent_id, c.title, c.metadata, c.created_at, c.updated_at, c.summary, c.owner_id, COUNT(m.id)::int AS message_count FROM conversations c
JOIN agents a ON c.agent_id = a.id
LEFT JOIN messages m ON m.conversation_id = c.id AND m.owner_id = c.owner_id
WHERE a.visible = true
AND c.owner_id = $1
AND ($2::uuid IS NULL OR c.agent_id = $2)
GROUP BY c.id
ORDER BY c.updated_at DESC
`

type ListConversationsParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

type ListConversationsRow struct {
	ID           pgtype.UUID        `json:"id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Title        pgtype.Text        `json:"title"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Summary      pgtype.Text        `json:"summary"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	MessageCount int32              `json:"message_count"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.OwnerID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
			&i.OwnerID,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.role, m.content, m.metadata, m.created_at, m.owner_id FROM messages m
JOIN conversations c ON m.conversation_id = c.id
WHERE m.conversation_id = $1 AND c.owner_id = $2
ORDER BY m.created_at ASC
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET title = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationParams struct {
	ID      pgtype.UUID `json:"id"`
	Title   pgtype.Text `json:"title"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Title, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const updateConversationMetadata = `-- name: UpdateConversationMetadata :one
UPDATE conversations SET metadata = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
	OwnerID  pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateConversationMetadata(ctx context.Context, arg UpdateConversationMetadataParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationMetadata, arg.ID, arg.Metadata, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const updateConversationSummary = `-- name: UpdateConversationSummary :one
UPDATE conversations SET summary = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationSummaryParams struct {
	ID      pgtype.UUID `json:"id"`
	Summary pgtype.Text `json:"summary"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateConversationSummary(ctx context.Context, arg UpdateConversationSummaryParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationSummary, arg.ID, arg.Summary, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}
