// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (agent_id, title, metadata)
VALUES ($1, $2, $3)
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type CreateConversationParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	Title    pgtype.Text `json:"title"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.AgentID, arg.Title, arg.Metadata)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, role, content, metadata, created_at, owner_id
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

// Deletes a conversation and (via ON DELETE CASCADE) its messages. Used to roll
// back a freshly-created conversation when the very first chat turn fails before
// streaming, so a failed send never leaves an orphan conversation behind.
func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deleteLastExchange = `-- name: DeleteLastExchange :execrows
WITH last_user AS (
    SELECT id FROM messages
    WHERE messages.conversation_id = $1 AND messages.role = 'user'
    ORDER BY messages.created_at DESC LIMIT 1
),
last_assistant AS (
    SELECT id FROM messages
    WHERE messages.conversation_id = $1 AND messages.role = 'assistant'
    ORDER BY messages.created_at DESC LIMIT 1
)
DELETE FROM messages WHERE id IN (SELECT id FROM last_user) OR id IN (SELECT id FROM last_assistant)
`

func (q *Queries) DeleteLastExchange(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLastExchange, conversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :execrows
DELETE FROM messages WHERE conversation_id = $1
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesByConversation, conversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one
SELECT id, agent_id, title, metadata, created_at, updated_at, summary, owner_id FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const getLastUserMessage = `-- name: GetLastUserMessage :one
SELECT id, conversation_id, role, content, metadata, created_at, owner_id FROM messages
WHERE conversation_id = $1 AND role = 'user'
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastUserMessage(ctx context.Context, conversationID pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getLastUserMessage, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.agent_id, c.title, c.metadata, c.created_at, c.updated_at, c.summary, c.owner_id FROM conversations c
JOIN agents a ON c.agent_id = a.id
WHERE a.visible = true
AND ($1::uuid IS NULL OR c.agent_id = $1)
ORDER BY c.updated_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, dollar_1 pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, metadata, created_at, owner_id FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const updateConversationMetadata = `-- name: UpdateConversationMetadata :one
UPDATE conversations SET metadata = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateConversationMetadata(ctx context.Context, arg UpdateConversationMetadataParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationMetadata, arg.ID, arg.Metadata)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}

const updateConversationSummary = `-- name: UpdateConversationSummary :one
UPDATE conversations SET summary = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, agent_id, title, metadata, created_at, updated_at, summary, owner_id
`

type UpdateConversationSummaryParams struct {
	ID      pgtype.UUID `json:"id"`
	Summary pgtype.Text `json:"summary"`
}

func (q *Queries) UpdateConversationSummary(ctx context.Context, arg UpdateConversationSummaryParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationSummary, arg.ID, arg.Summary)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.OwnerID,
	)
	return i, err
}
