// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (agent_id, title, metadata)
VALUES ($1, $2, $3)
RETURNING id, agent_id, title, metadata, created_at, updated_at
`

type CreateConversationParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	Title    pgtype.Text `json:"title"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.AgentID, arg.Title, arg.Metadata)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, role, content, metadata, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, agent_id, title, metadata, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, agent_id, title, metadata, created_at, updated_at FROM conversations
WHERE ($1::uuid IS NULL OR agent_id = $1)
ORDER BY updated_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, dollar_1 pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, metadata, created_at FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, agent_id, title, metadata, created_at, updated_at
`

type UpdateConversationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Title,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
