// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: correlation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkUnits = `-- name: CountWorkUnits :one
SELECT COUNT(*) FROM (
    SELECT 1 FROM work_events
    WHERE ($1::text = '' OR tenant = $1::text)
    GROUP BY tenant, project_id, external_ref, branch, sha
) g
`

// Consistent with ListWorkUnits grouping (same key + same tenant filter) so Total matches.
func (q *Queries) CountWorkUnits(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkUnits, tenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkUnitEvents = `-- name: GetWorkUnitEvents :many
SELECT id, event_id, schema_version, harness, session_id, host, pid, kind, status, liveness_mode, project_id, tenant, external_ref, branch, sha, cwd, title, cost_usd, payload, ts, received_at
FROM work_events
WHERE COALESCE(tenant, '')            = $1
  AND COALESCE(project_id::text, '')  = $2
  AND COALESCE(external_ref, '')      = $3
  AND COALESCE(branch, '')            = $4
  AND COALESCE(sha, '')               = $5
ORDER BY received_at ASC
`

type GetWorkUnitEventsParams struct {
	Tenant      string      `json:"tenant"`
	ProjectID   pgtype.UUID `json:"project_id"`
	ExternalRef pgtype.Text `json:"external_ref"`
	Branch      pgtype.Text `json:"branch"`
	Sha         pgtype.Text `json:"sha"`
}

// All events in one group (drill-down). Matches the same 5-part key as ListWorkUnits,
// NULL-safe so the uncorrelated buckets match rows with NULL key parts.
func (q *Queries) GetWorkUnitEvents(ctx context.Context, arg GetWorkUnitEventsParams) ([]WorkEvent, error) {
	rows, err := q.db.Query(ctx, getWorkUnitEvents,
		arg.Tenant,
		arg.ProjectID,
		arg.ExternalRef,
		arg.Branch,
		arg.Sha,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkEvent
	for rows.Next() {
		var i WorkEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SchemaVersion,
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.Pid,
			&i.Kind,
			&i.Status,
			&i.LivenessMode,
			&i.ProjectID,
			&i.Tenant,
			&i.ExternalRef,
			&i.Branch,
			&i.Sha,
			&i.Cwd,
			&i.Title,
			&i.CostUsd,
			&i.Payload,
			&i.Ts,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkUnits = `-- name: ListWorkUnits :many

WITH session_state AS (
    SELECT
        tenant, project_id, external_ref, branch, sha, harness, session_id,
        COUNT(*)                          AS sess_events,
        MIN(received_at)                  AS sess_first,
        MAX(received_at)                  AS sess_last,
        (array_agg(status ORDER BY received_at DESC)
            FILTER (WHERE status IS NOT NULL
                    AND kind IN ('session.start', 'session.heartbeat', 'session.end')))[1] AS sess_status,
        (array_agg(title ORDER BY received_at DESC)
            FILTER (WHERE title IS NOT NULL AND title <> ''))[1] AS sess_title,
        (array_agg(kind ORDER BY received_at DESC))[1] AS sess_kind,
        MAX(cost_usd)                     AS sess_cost
    FROM work_events
    WHERE ($3::text = '' OR tenant = $3::text)
    GROUP BY tenant, project_id, external_ref, branch, sha, harness, session_id
),
session_live AS (
    SELECT tenant, project_id, external_ref, branch, sha, harness, session_id, sess_events, sess_first, sess_last, sess_status, sess_title, sess_kind, sess_cost,
        CASE
            WHEN sess_status = 'failed'              THEN 'failed'
            WHEN sess_status IN ('done', 'cancelled') THEN 'done'
            WHEN NOW() - sess_last > interval '5 minutes' THEN 'stale'
            ELSE 'running'
        END AS sess_liveness
    FROM session_state
)
SELECT
    COALESCE(tenant, '')                  AS tenant,
    COALESCE(project_id::text, '')::text  AS project_key,
    COALESCE(external_ref, '')            AS external_ref,
    COALESCE(branch, '')                  AS branch,
    COALESCE(sha, '')                     AS sha,
    SUM(sess_events)::bigint              AS event_count,
    COUNT(*)::bigint                      AS session_count,
    MIN(sess_first)::timestamptz          AS first_event_at,
    MAX(sess_last)::timestamptz           AS last_event_at,
    (external_ref IS NOT NULL OR branch IS NOT NULL OR sha IS NOT NULL) AS correlated,
    -- Unit liveness with precedence (B2). Computed from the server clock.
    CASE
        WHEN bool_or(sess_liveness = 'failed')  THEN 'failed'
        WHEN bool_or(sess_liveness = 'running') THEN 'running'
        WHEN bool_or(sess_liveness = 'stale')   THEN 'stale'
        ELSE 'done'
    END::text                             AS liveness,
    -- Sessions still alive (running or stale) — lets the card show "N active" honestly.
    COUNT(*) FILTER (WHERE sess_liveness IN ('running', 'stale'))::bigint AS active_session_count,
    COALESCE((array_agg(sess_title ORDER BY sess_last DESC) FILTER (WHERE sess_title IS NOT NULL))[1], '')::text AS title,
    COALESCE((array_agg(sess_kind ORDER BY sess_last DESC))[1], '')::text AS latest_kind,
    (array_agg(DISTINCT harness))::text[] AS harnesses,
    -- SUM of per-session final cost (cumulative per session, contract §6) = correct unit total.
    (SUM(sess_cost))::numeric             AS cost_usd
FROM session_live
GROUP BY tenant, project_id, external_ref, branch, sha
ORDER BY MAX(sess_last) DESC,
         COALESCE(tenant,''), COALESCE(project_id::text,''),
         COALESCE(external_ref,''), COALESCE(branch,''), COALESCE(sha,'')
LIMIT $2 OFFSET $1
`

type ListWorkUnitsParams struct {
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
	Tenant string `json:"tenant"`
}

type ListWorkUnitsRow struct {
	Tenant             string             `json:"tenant"`
	ProjectKey         string             `json:"project_key"`
	ExternalRef        string             `json:"external_ref"`
	Branch             string             `json:"branch"`
	Sha                string             `json:"sha"`
	EventCount         int64              `json:"event_count"`
	SessionCount       int64              `json:"session_count"`
	FirstEventAt       pgtype.Timestamptz `json:"first_event_at"`
	LastEventAt        pgtype.Timestamptz `json:"last_event_at"`
	Correlated         pgtype.Bool        `json:"correlated"`
	Liveness           string             `json:"liveness"`
	ActiveSessionCount int64              `json:"active_session_count"`
	Title              string             `json:"title"`
	LatestKind         string             `json:"latest_kind"`
	Harnesses          []string           `json:"harnesses"`
	CostUsd            pgtype.Numeric     `json:"cost_usd"`
}

// WP-B correlation engine. Groups work_events into work_units by the correlation key.
// Per contract §7 the key is (project_id, external_ref, branch, sha); we ALSO group by
// `tenant` so two tenants emitting the same external_ref with a NULL project_id are never
// merged into one unit (ADR-002 D6 — employer tenants never co-mingle).
// Events sharing no code/tracker anchor are surfaced as `correlated=false` units, grouped
// by their (tenant, project) context — NEVER dropped (ADR-001 F3). The no-drop invariant:
// SUM(event_count) over all units == COUNT(*) of work_events.
// Two-level aggregation so liveness is honest (review findings B1/B2/B5):
//  1. session_state: collapse each (key, harness, session_id) to ONE session, taking its
//     latest LIFECYCLE status (only session.start/heartbeat/end drive status — a later
//     artifact.created/note with status='unknown' must NOT mask a terminal session: B1).
//  2. session_live: derive per-session liveness from the SERVER clock NOW() (contract §4:
//     received_at is the only liveness clock — so we compute it here, not on the browser).
//  3. outer: aggregate sessions into the unit with precedence failed>running>stale>done (B2),
//     and SUM per-session cost (cumulative per session) for a correct unit total (B5).
//
// Optional tenant filter (B3): @tenant = ” returns all tenants; otherwise scopes to one.
func (q *Queries) ListWorkUnits(ctx context.Context, arg ListWorkUnitsParams) ([]ListWorkUnitsRow, error) {
	rows, err := q.db.Query(ctx, listWorkUnits, arg.Off, arg.Lim, arg.Tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkUnitsRow
	for rows.Next() {
		var i ListWorkUnitsRow
		if err := rows.Scan(
			&i.Tenant,
			&i.ProjectKey,
			&i.ExternalRef,
			&i.Branch,
			&i.Sha,
			&i.EventCount,
			&i.SessionCount,
			&i.FirstEventAt,
			&i.LastEventAt,
			&i.Correlated,
			&i.Liveness,
			&i.ActiveSessionCount,
			&i.Title,
			&i.LatestKind,
			&i.Harnesses,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
