// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: correlation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkUnits = `-- name: CountWorkUnits :one
SELECT COUNT(*) FROM (
    SELECT 1 FROM work_events
    GROUP BY tenant, project_id, external_ref, branch, sha
) g
`

// Consistent with ListWorkUnits grouping (same key) so pagination Total matches.
func (q *Queries) CountWorkUnits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkUnits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkUnitEvents = `-- name: GetWorkUnitEvents :many
SELECT id, event_id, schema_version, harness, session_id, host, pid, kind, status, liveness_mode, project_id, tenant, external_ref, branch, sha, cwd, title, cost_usd, payload, ts, received_at
FROM work_events
WHERE COALESCE(tenant, '')            = $1
  AND COALESCE(project_id::text, '')  = $2
  AND COALESCE(external_ref, '')      = $3
  AND COALESCE(branch, '')            = $4
  AND COALESCE(sha, '')               = $5
ORDER BY received_at ASC
`

type GetWorkUnitEventsParams struct {
	Tenant      string      `json:"tenant"`
	ProjectID   pgtype.UUID `json:"project_id"`
	ExternalRef pgtype.Text `json:"external_ref"`
	Branch      pgtype.Text `json:"branch"`
	Sha         pgtype.Text `json:"sha"`
}

// All events in one group (drill-down). Matches the same 5-part key as ListWorkUnits,
// NULL-safe so the uncorrelated buckets match rows with NULL key parts.
func (q *Queries) GetWorkUnitEvents(ctx context.Context, arg GetWorkUnitEventsParams) ([]WorkEvent, error) {
	rows, err := q.db.Query(ctx, getWorkUnitEvents,
		arg.Tenant,
		arg.ProjectID,
		arg.ExternalRef,
		arg.Branch,
		arg.Sha,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkEvent
	for rows.Next() {
		var i WorkEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SchemaVersion,
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.Pid,
			&i.Kind,
			&i.Status,
			&i.LivenessMode,
			&i.ProjectID,
			&i.Tenant,
			&i.ExternalRef,
			&i.Branch,
			&i.Sha,
			&i.Cwd,
			&i.Title,
			&i.CostUsd,
			&i.Payload,
			&i.Ts,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkUnits = `-- name: ListWorkUnits :many

SELECT
    COALESCE(tenant, '')                  AS tenant,
    COALESCE(project_id::text, '')::text  AS project_key,
    COALESCE(external_ref, '')            AS external_ref,
    COALESCE(branch, '')                  AS branch,
    COALESCE(sha, '')                     AS sha,
    COUNT(*)                              AS event_count,
    COUNT(DISTINCT (harness || ':' || session_id)) AS session_count,
    MIN(received_at)::timestamptz         AS first_event_at,
    MAX(received_at)::timestamptz         AS last_event_at,
    (external_ref IS NOT NULL OR branch IS NOT NULL OR sha IS NOT NULL) AS correlated,
    -- Latest status drives liveness honestly (F10): the status of the most recent
    -- event in the group, ignoring rows that carry no status (e.g. artifact.created).
    -- COALESCE to '' so a group of only status-less events scans cleanly (not NULL).
    COALESCE((array_agg(status ORDER BY received_at DESC) FILTER (WHERE status IS NOT NULL))[1], '')::text AS latest_status,
    -- Latest event kind (for the drill-down / uncorrelated label).
    COALESCE((array_agg(kind ORDER BY received_at DESC))[1], '')::text AS latest_kind,
    -- Most recent non-empty title.
    COALESCE((array_agg(title ORDER BY received_at DESC) FILTER (WHERE title IS NOT NULL AND title <> ''))[1], '')::text AS title,
    -- Distinct harnesses that contributed (for the harness pills).
    (array_agg(DISTINCT harness))::text[] AS harnesses,
    -- cost_usd is cumulative per session (contract §6); MAX is exact for a single-session
    -- unit. Multi-session units may undercount — acceptable for v1 display. NULL when no
    -- event carried a cost; stays nullable so the UI can omit it rather than show $0.00.
    (MAX(cost_usd))::numeric AS cost_usd
FROM work_events
GROUP BY tenant, project_id, external_ref, branch, sha
ORDER BY MAX(received_at) DESC,
         COALESCE(tenant,''), COALESCE(project_id::text,''),
         COALESCE(external_ref,''), COALESCE(branch,''), COALESCE(sha,'')
LIMIT $1 OFFSET $2
`

type ListWorkUnitsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListWorkUnitsRow struct {
	Tenant       string             `json:"tenant"`
	ProjectKey   string             `json:"project_key"`
	ExternalRef  string             `json:"external_ref"`
	Branch       string             `json:"branch"`
	Sha          string             `json:"sha"`
	EventCount   int64              `json:"event_count"`
	SessionCount int64              `json:"session_count"`
	FirstEventAt pgtype.Timestamptz `json:"first_event_at"`
	LastEventAt  pgtype.Timestamptz `json:"last_event_at"`
	Correlated   pgtype.Bool        `json:"correlated"`
	LatestStatus string             `json:"latest_status"`
	LatestKind   string             `json:"latest_kind"`
	Title        string             `json:"title"`
	Harnesses    []string           `json:"harnesses"`
	CostUsd      pgtype.Numeric     `json:"cost_usd"`
}

// WP-B correlation engine. Groups work_events into work_units by the correlation key.
// Per contract §7 the key is (project_id, external_ref, branch, sha); we ALSO group by
// `tenant` so two tenants emitting the same external_ref with a NULL project_id are never
// merged into one unit (ADR-002 D6 — employer tenants never co-mingle).
// Events sharing no code/tracker anchor are surfaced as `correlated=false` units, grouped
// by their (tenant, project) context — NEVER dropped (ADR-001 F3). The no-drop invariant:
// SUM(event_count) over all units == COUNT(*) of work_events.
func (q *Queries) ListWorkUnits(ctx context.Context, arg ListWorkUnitsParams) ([]ListWorkUnitsRow, error) {
	rows, err := q.db.Query(ctx, listWorkUnits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkUnitsRow
	for rows.Next() {
		var i ListWorkUnitsRow
		if err := rows.Scan(
			&i.Tenant,
			&i.ProjectKey,
			&i.ExternalRef,
			&i.Branch,
			&i.Sha,
			&i.EventCount,
			&i.SessionCount,
			&i.FirstEventAt,
			&i.LastEventAt,
			&i.Correlated,
			&i.LatestStatus,
			&i.LatestKind,
			&i.Title,
			&i.Harnesses,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
