// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanStaleDelegations = `-- name: CleanStaleDelegations :exec
UPDATE delegations SET status = 'interrupted', completed_at = now(), result_summary = 'Stale delegation — auto-cleaned (no completion webhook received within timeout).'
WHERE status = 'running' AND created_at < now() - INTERVAL '30 minutes'
`

func (q *Queries) CleanStaleDelegations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanStaleDelegations)
	return err
}

const countDelegations = `-- name: CountDelegations :one
SELECT COUNT(*) FROM delegations
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR parent_agent_id = $2)
  AND ($3::text = '' OR status = $3)
`

type CountDelegationsParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
}

func (q *Queries) CountDelegations(ctx context.Context, arg CountDelegationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDelegations, arg.OwnerID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelegation = `-- name: CreateDelegation :one
INSERT INTO delegations (owner_id, parent_agent_id, child_agent_name, task_goal, status, result_summary, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_agent_id, child_agent_name, task_goal, status, result_summary, created_at, completed_at, metadata, owner_id
`

type CreateDelegationParams struct {
	OwnerID        pgtype.UUID `json:"owner_id"`
	ParentAgentID  pgtype.UUID `json:"parent_agent_id"`
	ChildAgentName string      `json:"child_agent_name"`
	TaskGoal       string      `json:"task_goal"`
	Status         string      `json:"status"`
	ResultSummary  pgtype.Text `json:"result_summary"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, createDelegation,
		arg.OwnerID,
		arg.ParentAgentID,
		arg.ChildAgentName,
		arg.TaskGoal,
		arg.Status,
		arg.ResultSummary,
		arg.Metadata,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ParentAgentID,
		&i.ChildAgentName,
		&i.TaskGoal,
		&i.Status,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.OwnerID,
	)
	return i, err
}

const getDelegation = `-- name: GetDelegation :one
SELECT id, parent_agent_id, child_agent_name, task_goal, status, result_summary, created_at, completed_at, metadata, owner_id FROM delegations WHERE id = $1 AND owner_id = $2
`

type GetDelegationParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetDelegation(ctx context.Context, arg GetDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegation, arg.ID, arg.OwnerID)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ParentAgentID,
		&i.ChildAgentName,
		&i.TaskGoal,
		&i.Status,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.OwnerID,
	)
	return i, err
}

const listDelegations = `-- name: ListDelegations :many
SELECT id, parent_agent_id, child_agent_name, task_goal, status, result_summary, created_at, completed_at, metadata, owner_id FROM delegations
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR parent_agent_id = $2)
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDelegationsParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Column2 pgtype.UUID `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDelegations(ctx context.Context, arg ListDelegationsParams) ([]Delegation, error) {
	rows, err := q.db.Query(ctx, listDelegations,
		arg.OwnerID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.ParentAgentID,
			&i.ChildAgentName,
			&i.TaskGoal,
			&i.Status,
			&i.ResultSummary,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelegation = `-- name: UpdateDelegation :one
UPDATE delegations SET status = $2, result_summary = COALESCE($3, result_summary), completed_at = CASE WHEN $2 IN ('completed','failed','interrupted') THEN now() ELSE completed_at END, metadata = COALESCE($4, metadata)
WHERE id = $1 AND owner_id = $5
RETURNING id, parent_agent_id, child_agent_name, task_goal, status, result_summary, created_at, completed_at, metadata, owner_id
`

type UpdateDelegationParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	ResultSummary pgtype.Text `json:"result_summary"`
	Metadata      []byte      `json:"metadata"`
	OwnerID       pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateDelegation(ctx context.Context, arg UpdateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, updateDelegation,
		arg.ID,
		arg.Status,
		arg.ResultSummary,
		arg.Metadata,
		arg.OwnerID,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ParentAgentID,
		&i.ChildAgentName,
		&i.TaskGoal,
		&i.Status,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.OwnerID,
	)
	return i, err
}
