// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emitters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmitterHealthSessions = `-- name: CountEmitterHealthSessions :one
SELECT COUNT(DISTINCT (harness, session_id))::bigint AS total
FROM work_events
WHERE tenant = $1::text
`

// Returns total count of distinct (harness, session_id) matching the tenant filter.
func (q *Queries) CountEmitterHealthSessions(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countEmitterHealthSessions, tenant)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getEmitterHealth = `-- name: GetEmitterHealth :many
WITH session_agg AS (
    -- For each (harness, session_id), compute the session-level state.
    -- IMPORTANT: liveness_mode and host are aggregated per session from
    -- start/heartbeat events, NOT read from the arbitrary latest row.
    -- A note/artifact.created (NULL liveness_mode) as the latest row must
    -- NOT cause a live supervised emitter to be reported stale.
    SELECT DISTINCT ON (harness, session_id)
        harness,
        session_id,
        -- Latest terminal event, if any (session.end).
        MAX(CASE WHEN kind = 'session.end' AND status IN ('done','failed','cancelled')
                 THEN status END) OVER (PARTITION BY harness, session_id)
            AS terminal_status,
        -- Last heartbeat/start received_at (for supervised liveness check).
        MAX(received_at) FILTER (
            WHERE kind IN ('session.start', 'session.heartbeat')
        ) OVER (PARTITION BY harness, session_id)
            AS last_heartbeat,
        -- Latest received_at across all events for this session.
        MAX(received_at) OVER (PARTITION BY harness, session_id)
            AS last_event_received_at,
        -- Latest status seen.
        MAX(status) OVER (PARTITION BY harness, session_id)
            AS last_status,
        -- Tenant from the session (consistent within a session).
        MAX(tenant) OVER (PARTITION BY harness, session_id)
            AS tenant,
        -- Earliest received_at (session start time).
        MIN(received_at) OVER (PARTITION BY harness, session_id)
            AS first_seen,
        -- PID from latest event (if any).
        MAX(pid) OVER (PARTITION BY harness, session_id)
            AS pid,
        -- Per-session liveness_mode: aggregate from start/heartbeat, never from
        -- arbitrary latest row (note/artifact.created legitimately have NULL mode).
        MAX(liveness_mode) FILTER (
            WHERE kind IN ('session.start', 'session.heartbeat')
        ) OVER (PARTITION BY harness, session_id)
            AS session_mode,
        -- Per-session host: derive from start/heartbeat, not from arbitrary latest row.
        MAX(host) FILTER (
            WHERE kind IN ('session.start', 'session.heartbeat')
        ) OVER (PARTITION BY harness, session_id)
            AS session_host
    FROM work_events
    WHERE tenant = $4::text
    ORDER BY harness, session_id, received_at DESC
),
deduped AS (
    SELECT DISTINCT ON (harness, session_id)
        harness,
        session_id,
        session_host AS host,
        session_mode AS liveness_mode,
        terminal_status,
        last_heartbeat,
        last_event_received_at,
        last_status,
        tenant,
        first_seen,
        pid
    FROM session_agg
    ORDER BY harness, session_id
)
SELECT
    harness,
    session_id,
    host,
    liveness_mode,
    COALESCE(pid::int, 0) AS pid,
    -- Derived liveness state (contract §4):
    CASE
        WHEN terminal_status IS NOT NULL THEN
            -- Terminal seen → absorbing state. Report the terminal status.
            LOWER(terminal_status)
        WHEN liveness_mode = 'supervised' THEN
            CASE
                WHEN last_heartbeat IS NOT NULL
                     AND (NOW() - last_heartbeat) < ($1::interval)
                THEN 'running'
                ELSE 'stale'
            END
        WHEN liveness_mode = 'bounded' THEN
            -- Bounded emitters can't heartbeat.
            -- Without host-process-reporter (WP-N), we use age > 6h as stale backstop.
            -- If last event is recent, tentatively 'running' (no proof from reporter yet).
            CASE
                WHEN last_event_received_at IS NOT NULL
                     AND (NOW() - last_event_received_at) < INTERVAL '6 hours'
                THEN 'running'
                ELSE 'stale'
            END
        ELSE 'stale'  -- unknown mode
    END AS status,
    -- Human-readable last-seen (latest received_at from any event).
    last_event_received_at,
    -- For supervised: last heartbeat time specifically.
    last_heartbeat,
    first_seen
FROM deduped
ORDER BY last_event_received_at DESC NULLS LAST
LIMIT $3::int OFFSET $2::int
`

type GetEmitterHealthParams struct {
	StaleWindow pgtype.Interval `json:"stale_window"`
	Off         int32           `json:"off"`
	Lim         int32           `json:"lim"`
	Tenant      string          `json:"tenant"`
}

type GetEmitterHealthRow struct {
	Harness             string      `json:"harness"`
	SessionID           string      `json:"session_id"`
	Host                interface{} `json:"host"`
	LivenessMode        interface{} `json:"liveness_mode"`
	Pid                 interface{} `json:"pid"`
	Status              string      `json:"status"`
	LastEventReceivedAt interface{} `json:"last_event_received_at"`
	LastHeartbeat       interface{} `json:"last_heartbeat"`
	FirstSeen           interface{} `json:"first_seen"`
}

// Returns per-session liveness state derived from work_events.
// Pure read — no migration needed (WP-M).
// Computes liveness as a PURE FUNCTION of (persisted events, server clock now).
// Contract §4: running requires positive proof (heartbeat within timeout);
// absence of proof ⇒ stale, never "running" (ADR-001 F10 / ADR-003 D3).
// Terminal (session.end) is absorbing: once seen, later non-terminal events are
// ignored for liveness purposes.
// @stale_window: supervised sessions with no heartbeat in this window are stale.
//
//	Default = 5 minutes (contract §4).
//
// @tenant: required — scopes to one tenant (handler rejects empty).
func (q *Queries) GetEmitterHealth(ctx context.Context, arg GetEmitterHealthParams) ([]GetEmitterHealthRow, error) {
	rows, err := q.db.Query(ctx, getEmitterHealth,
		arg.StaleWindow,
		arg.Off,
		arg.Lim,
		arg.Tenant,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmitterHealthRow
	for rows.Next() {
		var i GetEmitterHealthRow
		if err := rows.Scan(
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.LivenessMode,
			&i.Pid,
			&i.Status,
			&i.LastEventReceivedAt,
			&i.LastHeartbeat,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
