// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (title, description, status, progress, target_date, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, status, progress, target_date, metadata, created_at, updated_at, owner_id
`

type CreateGoalParams struct {
	Title       string        `json:"title"`
	Description pgtype.Text   `json:"description"`
	Status      string        `json:"status"`
	Progress    pgtype.Float4 `json:"progress"`
	TargetDate  pgtype.Date   `json:"target_date"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Progress,
		arg.TargetDate,
		arg.Metadata,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.TargetDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1
`

func (q *Queries) DeleteGoal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoal, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, title, description, status, progress, target_date, metadata, created_at, updated_at, owner_id FROM goals WHERE id = $1
`

func (q *Queries) GetGoal(ctx context.Context, id pgtype.UUID) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.TargetDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, title, description, status, progress, target_date, metadata, created_at, updated_at, owner_id FROM goals ORDER BY created_at DESC
`

func (q *Queries) ListGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Progress,
			&i.TargetDate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals SET title = $2, description = $3, status = $4, progress = $5, target_date = $6, metadata = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, status, progress, target_date, metadata, created_at, updated_at, owner_id
`

type UpdateGoalParams struct {
	ID          pgtype.UUID   `json:"id"`
	Title       string        `json:"title"`
	Description pgtype.Text   `json:"description"`
	Status      string        `json:"status"`
	Progress    pgtype.Float4 `json:"progress"`
	TargetDate  pgtype.Date   `json:"target_date"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Progress,
		arg.TargetDate,
		arg.Metadata,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Progress,
		&i.TargetDate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
