// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: host_liveness.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHostLiveness = `-- name: CountHostLiveness :one
SELECT COUNT(*)::bigint FROM host_liveness
WHERE ($1::text = '' OR tenant = $1::text)
AND owner_id = $2
`

type CountHostLivenessParams struct {
	Tenant  string      `json:"tenant"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Counts liveness records matching the tenant filter.
func (q *Queries) CountHostLiveness(ctx context.Context, arg CountHostLivenessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHostLiveness, arg.Tenant, arg.OwnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getBoundedSessionHostLiveness = `-- name: GetBoundedSessionHostLiveness :one
SELECT COALESCE(hl.alive, false)::boolean AS alive
FROM (
    SELECT we_host.host AS host, we_host.pid AS pid
    FROM work_events AS we_host
    WHERE we_host.harness = $1
      AND we_host.session_id = $2
      AND we_host.tenant = $3
      AND we_host.kind = 'session.start'
    ORDER BY we_host.received_at DESC
    LIMIT 1
) sess
LEFT JOIN host_liveness hl
    ON hl.host = sess.host AND hl.pid = sess.pid AND hl.tenant = $3
    AND hl.owner_id = $4
`

type GetBoundedSessionHostLivenessParams struct {
	Harness   string      `json:"harness"`
	SessionID string      `json:"session_id"`
	Tenant    string      `json:"tenant"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

// Returns the latest host-liveness alive status for a bounded session.
// Joins the session's (host, pid) from work_events (kind=session.start) with
// host_liveness to get the latest alive report. COALESCE(NULL, false) means
// "no reporter proof → not alive" (contract §4: never running without proof).
//
// Derivation rule (consumed by deriveBoundedStatus in session_liveness.go):
//
//	alive=true  → session is running (positive proof from host reporter)
//	alive=false → session is stale (process killed/crashed)
//	no row      → no reporter proof → stale (NEVER running without proof)
//
// NOTE: seen_at freshness — the reporter only POSTs alive=true on first-seen
// and cwd-change. Long-running processes do NOT re-POST alive=true. The
// derivation must account for this (see session_liveness.go BoundedMaxAge
// backstop and the proposed seen_at TTL in the PR-body wiring diff).
func (q *Queries) GetBoundedSessionHostLiveness(ctx context.Context, arg GetBoundedSessionHostLivenessParams) (bool, error) {
	row := q.db.QueryRow(ctx, getBoundedSessionHostLiveness,
		arg.Harness,
		arg.SessionID,
		arg.Tenant,
		arg.OwnerID,
	)
	var alive bool
	err := row.Scan(&alive)
	return alive, err
}

const getHostLiveness = `-- name: GetHostLiveness :one
SELECT id, host, pid, session_id, harness, cwd, tenant, alive, seen_at, owner_id FROM host_liveness
WHERE host = $1 AND pid = $2
AND ($3::text = '' OR tenant = $3::text)
AND owner_id = $4
`

type GetHostLivenessParams struct {
	Host    string      `json:"host"`
	Pid     int32       `json:"pid"`
	Tenant  string      `json:"tenant"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Fetches a single host-liveness row by (host, pid).
// Optional tenant filter: returns rows only for matching tenant (or all if empty).
func (q *Queries) GetHostLiveness(ctx context.Context, arg GetHostLivenessParams) (HostLiveness, error) {
	row := q.db.QueryRow(ctx, getHostLiveness,
		arg.Host,
		arg.Pid,
		arg.Tenant,
		arg.OwnerID,
	)
	var i HostLiveness
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Pid,
		&i.SessionID,
		&i.Harness,
		&i.Cwd,
		&i.Tenant,
		&i.Alive,
		&i.SeenAt,
		&i.OwnerID,
	)
	return i, err
}

const listHostLiveness = `-- name: ListHostLiveness :many
SELECT id, host, pid, session_id, harness, cwd, tenant, alive, seen_at, owner_id FROM host_liveness
WHERE ($1::text = '' OR tenant = $1::text)
AND owner_id = $2
ORDER BY seen_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListHostLivenessParams struct {
	Tenant  string      `json:"tenant"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Off     int32       `json:"off"`
	Lim     int32       `json:"lim"`
}

// Lists all liveness records for a tenant, ordered by seen_at DESC.
// Returns all if tenant is empty.
func (q *Queries) ListHostLiveness(ctx context.Context, arg ListHostLivenessParams) ([]HostLiveness, error) {
	rows, err := q.db.Query(ctx, listHostLiveness,
		arg.Tenant,
		arg.OwnerID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostLiveness
	for rows.Next() {
		var i HostLiveness
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Pid,
			&i.SessionID,
			&i.Harness,
			&i.Cwd,
			&i.Tenant,
			&i.Alive,
			&i.SeenAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHostLiveness = `-- name: UpsertHostLiveness :one
INSERT INTO host_liveness (owner_id, host, pid, session_id, harness, cwd, tenant, alive)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (host, pid)
DO UPDATE SET
    session_id  = EXCLUDED.session_id,
    harness     = EXCLUDED.harness,
    cwd         = EXCLUDED.cwd,
    tenant      = EXCLUDED.tenant,
    alive       = EXCLUDED.alive,
    seen_at     = NOW()
RETURNING id, host, pid, session_id, harness, cwd, tenant, alive, seen_at, owner_id
`

type UpsertHostLivenessParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	Host      string      `json:"host"`
	Pid       int32       `json:"pid"`
	SessionID string      `json:"session_id"`
	Harness   string      `json:"harness"`
	Cwd       string      `json:"cwd"`
	Tenant    string      `json:"tenant"`
	Alive     bool        `json:"alive"`
}

// Upserts a host-liveness report keyed on (host, pid).
// This is the liveness *feed* (WP-N); session-state derivation is a
// separate consumer concern (WP-J / follow-on WPs).
func (q *Queries) UpsertHostLiveness(ctx context.Context, arg UpsertHostLivenessParams) (HostLiveness, error) {
	row := q.db.QueryRow(ctx, upsertHostLiveness,
		arg.OwnerID,
		arg.Host,
		arg.Pid,
		arg.SessionID,
		arg.Harness,
		arg.Cwd,
		arg.Tenant,
		arg.Alive,
	)
	var i HostLiveness
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Pid,
		&i.SessionID,
		&i.Harness,
		&i.Cwd,
		&i.Tenant,
		&i.Alive,
		&i.SeenAt,
		&i.OwnerID,
	)
	return i, err
}
