// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestkeys.sql

package db

import (
	"context"
)

const countActiveIngestKeys = `-- name: CountActiveIngestKeys :one
SELECT COUNT(*) FROM ingest_keys
WHERE tenant = $1 AND revoked_at IS NULL
`

// Count active (non-revoked) keys for a tenant.
func (q *Queries) CountActiveIngestKeys(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveIngestKeys, tenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestKey = `-- name: CreateIngestKey :one
INSERT INTO ingest_keys (key_hash, tenant, label)
VALUES ($1, $2, $3)
RETURNING id, key_hash, tenant, label, created_at, revoked_at
`

type CreateIngestKeyParams struct {
	KeyHash string `json:"key_hash"`
	Tenant  string `json:"tenant"`
	Label   string `json:"label"`
}

// Insert a new ingest key (hashed). The raw key is never stored — callers
// must hash before calling this.
func (q *Queries) CreateIngestKey(ctx context.Context, arg CreateIngestKeyParams) (IngestKey, error) {
	row := q.db.QueryRow(ctx, createIngestKey, arg.KeyHash, arg.Tenant, arg.Label)
	var i IngestKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Tenant,
		&i.Label,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getIngestKeyByHash = `-- name: GetIngestKeyByHash :one
SELECT id, key_hash, tenant, label, created_at, revoked_at FROM ingest_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

// Look up a (non-revoked) ingest key by its SHA-256 hash.
// Returns NULL (pgx.ErrNoRows) if not found or revoked.
func (q *Queries) GetIngestKeyByHash(ctx context.Context, keyHash string) (IngestKey, error) {
	row := q.db.QueryRow(ctx, getIngestKeyByHash, keyHash)
	var i IngestKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Tenant,
		&i.Label,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listIngestKeysByTenant = `-- name: ListIngestKeysByTenant :many
SELECT id, key_hash, tenant, label, created_at, revoked_at FROM ingest_keys
WHERE tenant = $1
ORDER BY created_at DESC
`

// List all (including revoked) keys for a tenant, newest first.
func (q *Queries) ListIngestKeysByTenant(ctx context.Context, tenant string) ([]IngestKey, error) {
	rows, err := q.db.Query(ctx, listIngestKeysByTenant, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestKey
	for rows.Next() {
		var i IngestKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.Tenant,
			&i.Label,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeIngestKey = `-- name: RevokeIngestKey :exec
UPDATE ingest_keys SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

// Revoke an ingest key by setting revoked_at to now.
func (q *Queries) RevokeIngestKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeIngestKey, id)
	return err
}
