// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppInstances = `-- name: CountAppInstances :one
SELECT COUNT(*)::bigint FROM app_instances
WHERE ($1::text = '' OR tenant = $1::text)
`

// Counts app instances matching the tenant filter (for pagination total).
func (q *Queries) CountAppInstances(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppInstances, tenant)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAppInstance = `-- name: CreateAppInstance :one
INSERT INTO app_instances (harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status, last_probed_at, last_heartbeat, created_at, updated_at
`

type CreateAppInstanceParams struct {
	Harness   string      `json:"harness"`
	SessionID string      `json:"session_id"`
	Host      string      `json:"host"`
	Pid       pgtype.Int4 `json:"pid"`
	Label     string      `json:"label"`
	HealthUrl string      `json:"health_url"`
	Branch    pgtype.Text `json:"branch"`
	Sha       pgtype.Text `json:"sha"`
	Cwd       pgtype.Text `json:"cwd"`
	Tenant    string      `json:"tenant"`
	Status    string      `json:"status"`
}

// Inserts a new app instance. Returns the created row.
func (q *Queries) CreateAppInstance(ctx context.Context, arg CreateAppInstanceParams) (AppInstance, error) {
	row := q.db.QueryRow(ctx, createAppInstance,
		arg.Harness,
		arg.SessionID,
		arg.Host,
		arg.Pid,
		arg.Label,
		arg.HealthUrl,
		arg.Branch,
		arg.Sha,
		arg.Cwd,
		arg.Tenant,
		arg.Status,
	)
	var i AppInstance
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Label,
		&i.HealthUrl,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Tenant,
		&i.Status,
		&i.LastProbedAt,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppInstance = `-- name: DeleteAppInstance :exec
DELETE FROM app_instances WHERE id = $1
`

// Deletes an app instance by ID.
func (q *Queries) DeleteAppInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppInstance, id)
	return err
}

const getAppInstance = `-- name: GetAppInstance :one
SELECT id, harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status, last_probed_at, last_heartbeat, created_at, updated_at FROM app_instances WHERE id = $1
`

// Fetches a single app instance by ID.
func (q *Queries) GetAppInstance(ctx context.Context, id pgtype.UUID) (AppInstance, error) {
	row := q.db.QueryRow(ctx, getAppInstance, id)
	var i AppInstance
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Label,
		&i.HealthUrl,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Tenant,
		&i.Status,
		&i.LastProbedAt,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppInstances = `-- name: ListAppInstances :many
SELECT id, harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status, last_probed_at, last_heartbeat, created_at, updated_at FROM app_instances
WHERE ($1::text = '' OR tenant = $1::text)
ORDER BY
    CASE WHEN status = 'up' THEN 0 ELSE 1 END,
    last_probed_at DESC NULLS LAST,
    created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListAppInstancesParams struct {
	Tenant string `json:"tenant"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

// Lists app instances scoped to a tenant. Returns all if tenant is empty.
// Supports pagination with limit/offset.
// Orders by last_probed_at DESC NULLS LAST (never-probed instances at end).
func (q *Queries) ListAppInstances(ctx context.Context, arg ListAppInstancesParams) ([]AppInstance, error) {
	rows, err := q.db.Query(ctx, listAppInstances, arg.Tenant, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInstance
	for rows.Next() {
		var i AppInstance
		if err := rows.Scan(
			&i.ID,
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.Pid,
			&i.Label,
			&i.HealthUrl,
			&i.Branch,
			&i.Sha,
			&i.Cwd,
			&i.Tenant,
			&i.Status,
			&i.LastProbedAt,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstanceDownByServerStopped = `-- name: MarkInstanceDownByServerStopped :exec
UPDATE app_instances
SET status    = 'down',
    updated_at = NOW()
WHERE host  = $1
  AND tenant = $2
  AND health_url IS NOT NULL
  AND health_url != ''
`

type MarkInstanceDownByServerStoppedParams struct {
	Host   string `json:"host"`
	Tenant string `json:"tenant"`
}

// Called when a server.stopped work-event arrives (contract §4).
// Sets status to 'down' — this is a definitive signal, not a probe.
func (q *Queries) MarkInstanceDownByServerStopped(ctx context.Context, arg MarkInstanceDownByServerStoppedParams) error {
	_, err := q.db.Exec(ctx, markInstanceDownByServerStopped, arg.Host, arg.Tenant)
	return err
}

const updateInstanceDown = `-- name: UpdateInstanceDown :exec
UPDATE app_instances
SET status    = 'down',
    updated_at = NOW()
WHERE id = $1
`

// Marks an instance as 'down' (from server.stopped event or probe failure).
func (q *Queries) UpdateInstanceDown(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateInstanceDown, id)
	return err
}

const updateInstanceProbeStatus = `-- name: UpdateInstanceProbeStatus :exec
UPDATE app_instances
SET status        = $1,
    last_probed_at = $2,
    updated_at     = NOW()
WHERE id = $3
`

type UpdateInstanceProbeStatusParams struct {
	Status       string             `json:"status"`
	LastProbedAt pgtype.Timestamptz `json:"last_probed_at"`
	ID           pgtype.UUID        `json:"id"`
}

// Updates the status and last_probed_at of an instance after a probe.
// This is the ONLY way status changes — never set from a work-event.
func (q *Queries) UpdateInstanceProbeStatus(ctx context.Context, arg UpdateInstanceProbeStatusParams) error {
	_, err := q.db.Exec(ctx, updateInstanceProbeStatus, arg.Status, arg.LastProbedAt, arg.ID)
	return err
}

const upsertAppInstanceByHostURL = `-- name: UpsertAppInstanceByHostURL :one
INSERT INTO app_instances (harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'unknown'
)
ON CONFLICT (host, health_url, tenant)
DO UPDATE SET
    session_id  = EXCLUDED.session_id,
    pid         = EXCLUDED.pid,
    branch      = EXCLUDED.branch,
    sha         = EXCLUDED.sha,
    label       = EXCLUDED.label,
    updated_at  = NOW()
WHERE app_instances.host = EXCLUDED.host
  AND app_instances.health_url = EXCLUDED.health_url
  AND app_instances.tenant = EXCLUDED.tenant
RETURNING id, harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status, last_probed_at, last_heartbeat, created_at, updated_at
`

type UpsertAppInstanceByHostURLParams struct {
	Harness   string      `json:"harness"`
	SessionID string      `json:"session_id"`
	Host      string      `json:"host"`
	Pid       pgtype.Int4 `json:"pid"`
	Label     string      `json:"label"`
	HealthUrl string      `json:"health_url"`
	Branch    pgtype.Text `json:"branch"`
	Sha       pgtype.Text `json:"sha"`
	Cwd       pgtype.Text `json:"cwd"`
	Tenant    string      `json:"tenant"`
}

// Upserts an instance keyed on (host, health_url, tenant).
// Used by server.started work-event auto-creation: if the same host+url+tenant
// already exists, updates its session_id, branch, sha, pid, and label.
// Does NOT change status — only a real probe updates status (anti-fake-status rule).
func (q *Queries) UpsertAppInstanceByHostURL(ctx context.Context, arg UpsertAppInstanceByHostURLParams) (AppInstance, error) {
	row := q.db.QueryRow(ctx, upsertAppInstanceByHostURL,
		arg.Harness,
		arg.SessionID,
		arg.Host,
		arg.Pid,
		arg.Label,
		arg.HealthUrl,
		arg.Branch,
		arg.Sha,
		arg.Cwd,
		arg.Tenant,
	)
	var i AppInstance
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Label,
		&i.HealthUrl,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Tenant,
		&i.Status,
		&i.LastProbedAt,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppInstanceOnServerStarted = `-- name: UpsertAppInstanceOnServerStarted :one
INSERT INTO app_instances (harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'unknown'
)
ON CONFLICT (host, health_url, tenant)
DO UPDATE SET
    session_id   = EXCLUDED.session_id,
    pid          = EXCLUDED.pid,
    branch       = EXCLUDED.branch,
    sha          = EXCLUDED.sha,
    label        = EXCLUDED.label,
    -- Only reset to unknown if currently down (server restarted)
    status       = CASE WHEN app_instances.status = 'down' THEN 'unknown' ELSE app_instances.status END,
    updated_at   = NOW()
WHERE app_instances.host = EXCLUDED.host
  AND app_instances.health_url = EXCLUDED.health_url
  AND app_instances.tenant = EXCLUDED.tenant
RETURNING id, harness, session_id, host, pid, label, health_url, branch, sha, cwd, tenant, status, last_probed_at, last_heartbeat, created_at, updated_at
`

type UpsertAppInstanceOnServerStartedParams struct {
	Harness   string      `json:"harness"`
	SessionID string      `json:"session_id"`
	Host      string      `json:"host"`
	Pid       pgtype.Int4 `json:"pid"`
	Label     string      `json:"label"`
	HealthUrl string      `json:"health_url"`
	Branch    pgtype.Text `json:"branch"`
	Sha       pgtype.Text `json:"sha"`
	Cwd       pgtype.Text `json:"cwd"`
	Tenant    string      `json:"tenant"`
}

// Called when a server.started work-event arrives (contract §4).
// Creates the instance if not known, or updates session/branch/sha.
// Status is set to 'unknown' only on creation (needs a real probe to go 'up').
func (q *Queries) UpsertAppInstanceOnServerStarted(ctx context.Context, arg UpsertAppInstanceOnServerStartedParams) (AppInstance, error) {
	row := q.db.QueryRow(ctx, upsertAppInstanceOnServerStarted,
		arg.Harness,
		arg.SessionID,
		arg.Host,
		arg.Pid,
		arg.Label,
		arg.HealthUrl,
		arg.Branch,
		arg.Sha,
		arg.Cwd,
		arg.Tenant,
	)
	var i AppInstance
	err := row.Scan(
		&i.ID,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Label,
		&i.HealthUrl,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Tenant,
		&i.Status,
		&i.LastProbedAt,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
