// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendFinding = `-- name: AppendFinding :one
INSERT INTO findings (pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, ts, pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary
`

type AppendFindingParams struct {
	PrRef       string      `json:"pr_ref"`
	WpRef       string      `json:"wp_ref"`
	Gate        int32       `json:"gate"`
	AuthorAgent string      `json:"author_agent"`
	Model       string      `json:"model"`
	Severity    string      `json:"severity"`
	Class       string      `json:"class"`
	RootCause   pgtype.Text `json:"root_cause"`
	Summary     pgtype.Text `json:"summary"`
}

func (q *Queries) AppendFinding(ctx context.Context, arg AppendFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, appendFinding,
		arg.PrRef,
		arg.WpRef,
		arg.Gate,
		arg.AuthorAgent,
		arg.Model,
		arg.Severity,
		arg.Class,
		arg.RootCause,
		arg.Summary,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.PrRef,
		&i.WpRef,
		&i.Gate,
		&i.AuthorAgent,
		&i.Model,
		&i.Severity,
		&i.Class,
		&i.RootCause,
		&i.Summary,
	)
	return i, err
}

const appendRunLog = `-- name: AppendRunLog :one
INSERT INTO run_log (event_type, pr_ref, wp_ref, summary, payload) VALUES ($1, $2, $3, $4, $5) RETURNING id, ts, event_type, pr_ref, wp_ref, summary, payload
`

type AppendRunLogParams struct {
	EventType string      `json:"event_type"`
	PrRef     string      `json:"pr_ref"`
	WpRef     string      `json:"wp_ref"`
	Summary   pgtype.Text `json:"summary"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) (RunLog, error) {
	row := q.db.QueryRow(ctx, appendRunLog,
		arg.EventType,
		arg.PrRef,
		arg.WpRef,
		arg.Summary,
		arg.Payload,
	)
	var i RunLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.EventType,
		&i.PrRef,
		&i.WpRef,
		&i.Summary,
		&i.Payload,
	)
	return i, err
}

const countFindings = `-- name: CountFindings :one
SELECT COUNT(*)::bigint FROM findings
`

func (q *Queries) CountFindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFindings)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFindingsByClass = `-- name: CountFindingsByClass :one
SELECT COUNT(*)::bigint FROM findings WHERE class = $1
`

func (q *Queries) CountFindingsByClass(ctx context.Context, class string) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingsByClass, class)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFindingsBySeverity = `-- name: CountFindingsBySeverity :one
SELECT COUNT(*)::bigint FROM findings WHERE severity = $1
`

func (q *Queries) CountFindingsBySeverity(ctx context.Context, severity string) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingsBySeverity, severity)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFindingsByWpRef = `-- name: CountFindingsByWpRef :one
SELECT COUNT(*)::bigint FROM findings WHERE wp_ref = $1
`

func (q *Queries) CountFindingsByWpRef(ctx context.Context, wpRef string) (int64, error) {
	row := q.db.QueryRow(ctx, countFindingsByWpRef, wpRef)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunLog = `-- name: CountRunLog :one
SELECT COUNT(*)::bigint FROM run_log
`

func (q *Queries) CountRunLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunLog)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunLogByWpRef = `-- name: CountRunLogByWpRef :one
SELECT COUNT(*)::bigint FROM run_log WHERE wp_ref = $1
`

func (q *Queries) CountRunLogByWpRef(ctx context.Context, wpRef string) (int64, error) {
	row := q.db.QueryRow(ctx, countRunLogByWpRef, wpRef)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listFindings = `-- name: ListFindings :many
SELECT id, ts, pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary FROM findings ORDER BY ts DESC LIMIT $1 OFFSET $2
`

type ListFindingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.PrRef,
			&i.WpRef,
			&i.Gate,
			&i.AuthorAgent,
			&i.Model,
			&i.Severity,
			&i.Class,
			&i.RootCause,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByClass = `-- name: ListFindingsByClass :many
SELECT id, ts, pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary FROM findings WHERE class = $1 ORDER BY ts DESC LIMIT $2 OFFSET $3
`

type ListFindingsByClassParams struct {
	Class  string `json:"class"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListFindingsByClass(ctx context.Context, arg ListFindingsByClassParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByClass, arg.Class, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.PrRef,
			&i.WpRef,
			&i.Gate,
			&i.AuthorAgent,
			&i.Model,
			&i.Severity,
			&i.Class,
			&i.RootCause,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsBySeverity = `-- name: ListFindingsBySeverity :many
SELECT id, ts, pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary FROM findings WHERE severity = $1 ORDER BY ts DESC LIMIT $2 OFFSET $3
`

type ListFindingsBySeverityParams struct {
	Severity string `json:"severity"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListFindingsBySeverity(ctx context.Context, arg ListFindingsBySeverityParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.PrRef,
			&i.WpRef,
			&i.Gate,
			&i.AuthorAgent,
			&i.Model,
			&i.Severity,
			&i.Class,
			&i.RootCause,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByWpRef = `-- name: ListFindingsByWpRef :many
SELECT id, ts, pr_ref, wp_ref, gate, author_agent, model, severity, class, root_cause, summary FROM findings WHERE wp_ref = $1 ORDER BY ts DESC LIMIT $2 OFFSET $3
`

type ListFindingsByWpRefParams struct {
	WpRef  string `json:"wp_ref"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListFindingsByWpRef(ctx context.Context, arg ListFindingsByWpRefParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByWpRef, arg.WpRef, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.PrRef,
			&i.WpRef,
			&i.Gate,
			&i.AuthorAgent,
			&i.Model,
			&i.Severity,
			&i.Class,
			&i.RootCause,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLog = `-- name: ListRunLog :many
SELECT id, ts, event_type, pr_ref, wp_ref, summary, payload FROM run_log ORDER BY ts DESC LIMIT $1 OFFSET $2
`

type ListRunLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRunLog(ctx context.Context, arg ListRunLogParams) ([]RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.PrRef,
			&i.WpRef,
			&i.Summary,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogByWpRef = `-- name: ListRunLogByWpRef :many
SELECT id, ts, event_type, pr_ref, wp_ref, summary, payload FROM run_log WHERE wp_ref = $1 ORDER BY ts DESC LIMIT $2 OFFSET $3
`

type ListRunLogByWpRefParams struct {
	WpRef  string `json:"wp_ref"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRunLogByWpRef(ctx context.Context, arg ListRunLogByWpRefParams) ([]RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLogByWpRef, arg.WpRef, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.EventType,
			&i.PrRef,
			&i.WpRef,
			&i.Summary,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurringFindings = `-- name: RecurringFindings :many
SELECT class, author_agent, wp_ref, COUNT(*)::bigint AS count
FROM findings
GROUP BY class, author_agent, wp_ref
HAVING COUNT(*) >= $1
ORDER BY count DESC
`

type RecurringFindingsRow struct {
	Class       string `json:"class"`
	AuthorAgent string `json:"author_agent"`
	WpRef       string `json:"wp_ref"`
	Count       int64  `json:"count"`
}

func (q *Queries) RecurringFindings(ctx context.Context, dollar_1 interface{}) ([]RecurringFindingsRow, error) {
	rows, err := q.db.Query(ctx, recurringFindings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringFindingsRow
	for rows.Next() {
		var i RecurringFindingsRow
		if err := rows.Scan(
			&i.Class,
			&i.AuthorAgent,
			&i.WpRef,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
