// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memory_index WHERE file_path = $1
`

func (q *Queries) DeleteMemory(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, deleteMemory, filePath)
	return err
}

const getMemoryByPath = `-- name: GetMemoryByPath :one
SELECT id, file_path, title, content, tags, last_indexed FROM memory_index WHERE file_path = $1
`

func (q *Queries) GetMemoryByPath(ctx context.Context, filePath string) (MemoryIndex, error) {
	row := q.db.QueryRow(ctx, getMemoryByPath, filePath)
	var i MemoryIndex
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.LastIndexed,
	)
	return i, err
}

const listMemoryIndex = `-- name: ListMemoryIndex :many
SELECT id, file_path, title, content, tags, last_indexed FROM memory_index ORDER BY last_indexed DESC
`

func (q *Queries) ListMemoryIndex(ctx context.Context) ([]MemoryIndex, error) {
	rows, err := q.db.Query(ctx, listMemoryIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryIndex
	for rows.Next() {
		var i MemoryIndex
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.LastIndexed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemory = `-- name: SearchMemory :many
SELECT id, file_path, title, content, tags, last_indexed FROM memory_index
WHERE to_tsvector('english', coalesce(content, '')) @@ websearch_to_tsquery('english', $1)
ORDER BY ts_rank(to_tsvector('english', coalesce(content, '')), websearch_to_tsquery('english', $1)) DESC
LIMIT $2
`

type SearchMemoryParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
}

func (q *Queries) SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]MemoryIndex, error) {
	rows, err := q.db.Query(ctx, searchMemory, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryIndex
	for rows.Next() {
		var i MemoryIndex
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.LastIndexed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemory = `-- name: UpsertMemory :one
INSERT INTO memory_index (file_path, title, content, tags)
VALUES ($1, $2, $3, $4)
ON CONFLICT (file_path) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    tags = EXCLUDED.tags,
    last_indexed = NOW()
RETURNING id, file_path, title, content, tags, last_indexed
`

type UpsertMemoryParams struct {
	FilePath string      `json:"file_path"`
	Title    pgtype.Text `json:"title"`
	Content  pgtype.Text `json:"content"`
	Tags     []string    `json:"tags"`
}

func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (MemoryIndex, error) {
	row := q.db.QueryRow(ctx, upsertMemory,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.Tags,
	)
	var i MemoryIndex
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.LastIndexed,
	)
	return i, err
}
