// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemoryByProject = `-- name: CountMemoryByProject :one
SELECT COUNT(*) FROM memory_index
WHERE owner_id = $1 AND (project_id = $2 OR $2 IS NULL)
`

type CountMemoryByProjectParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// Workspace surface (issue #134): how many notes belong to a project.
func (q *Queries) CountMemoryByProject(ctx context.Context, arg CountMemoryByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryByProject, arg.OwnerID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memory_index WHERE file_path = $1 AND owner_id = $2
`

type DeleteMemoryParams struct {
	FilePath string      `json:"file_path"`
	OwnerID  pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.FilePath, arg.OwnerID)
	return err
}

const getMemoryByPath = `-- name: GetMemoryByPath :one
SELECT id, file_path, title, content, tags, last_indexed, owner_id, project_id FROM memory_index WHERE file_path = $1 AND owner_id = $2
`

type GetMemoryByPathParams struct {
	FilePath string      `json:"file_path"`
	OwnerID  pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetMemoryByPath(ctx context.Context, arg GetMemoryByPathParams) (MemoryIndex, error) {
	row := q.db.QueryRow(ctx, getMemoryByPath, arg.FilePath, arg.OwnerID)
	var i MemoryIndex
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.LastIndexed,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}

const listMemoryIndex = `-- name: ListMemoryIndex :many
SELECT id, file_path, title, content, tags, last_indexed, owner_id, project_id FROM memory_index WHERE owner_id = $1 ORDER BY last_indexed DESC
`

func (q *Queries) ListMemoryIndex(ctx context.Context, ownerID pgtype.UUID) ([]MemoryIndex, error) {
	rows, err := q.db.Query(ctx, listMemoryIndex, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryIndex
	for rows.Next() {
		var i MemoryIndex
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.LastIndexed,
			&i.OwnerID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemory = `-- name: SearchMemory :many
SELECT id, file_path, title, content, tags, last_indexed, owner_id, project_id FROM memory_index
WHERE owner_id = $1
  AND to_tsvector('english', coalesce(content, '')) @@ websearch_to_tsquery('english', $2)
  AND (project_id = $4 OR $4 IS NULL)
ORDER BY ts_rank(to_tsvector('english', coalesce(content, '')), websearch_to_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchMemoryParams struct {
	OwnerID            pgtype.UUID `json:"owner_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
	Limit              int32       `json:"limit"`
	ProjectID          pgtype.UUID `json:"project_id"`
}

func (q *Queries) SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]MemoryIndex, error) {
	rows, err := q.db.Query(ctx, searchMemory,
		arg.OwnerID,
		arg.WebsearchToTsquery,
		arg.Limit,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryIndex
	for rows.Next() {
		var i MemoryIndex
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.LastIndexed,
			&i.OwnerID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemory = `-- name: UpsertMemory :one
INSERT INTO memory_index (owner_id, file_path, title, content, tags, project_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (file_path) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    tags = EXCLUDED.tags,
    project_id = EXCLUDED.project_id,
    last_indexed = NOW()
RETURNING id, file_path, title, content, tags, last_indexed, owner_id, project_id
`

type UpsertMemoryParams struct {
	OwnerID   pgtype.UUID `json:"owner_id"`
	FilePath  string      `json:"file_path"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Tags      []string    `json:"tags"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (MemoryIndex, error) {
	row := q.db.QueryRow(ctx, upsertMemory,
		arg.OwnerID,
		arg.FilePath,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.ProjectID,
	)
	var i MemoryIndex
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.LastIndexed,
		&i.OwnerID,
		&i.ProjectID,
	)
	return i, err
}
