// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ControlMode string

const (
	ControlModeContinuous ControlMode = "continuous"
	ControlModeTick       ControlMode = "tick"
	ControlModeStopped    ControlMode = "stopped"
)

func (e *ControlMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlMode(s)
	case string:
		*e = ControlMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlMode: %T", src)
	}
	return nil
}

type NullControlMode struct {
	ControlMode ControlMode `json:"control_mode"`
	Valid       bool        `json:"valid"` // Valid is true if ControlMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlMode) Scan(value interface{}) error {
	if value == nil {
		ns.ControlMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlMode), nil
}

type MailPriority string

const (
	MailPriorityLow    MailPriority = "low"
	MailPriorityNormal MailPriority = "normal"
	MailPriorityHigh   MailPriority = "high"
	MailPriorityUrgent MailPriority = "urgent"
)

func (e *MailPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailPriority(s)
	case string:
		*e = MailPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for MailPriority: %T", src)
	}
	return nil
}

type NullMailPriority struct {
	MailPriority MailPriority `json:"mail_priority"`
	Valid        bool         `json:"valid"` // Valid is true if MailPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailPriority) Scan(value interface{}) error {
	if value == nil {
		ns.MailPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailPriority), nil
}

type MailStatus string

const (
	MailStatusQueued    MailStatus = "queued"
	MailStatusDelivered MailStatus = "delivered"
	MailStatusRead      MailStatus = "read"
	MailStatusExpired   MailStatus = "expired"
)

func (e *MailStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailStatus(s)
	case string:
		*e = MailStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MailStatus: %T", src)
	}
	return nil
}

type NullMailStatus struct {
	MailStatus MailStatus `json:"mail_status"`
	Valid      bool       `json:"valid"` // Valid is true if MailStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MailStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailStatus), nil
}

type WorkUnitStatus string

const (
	WorkUnitStatusQueued   WorkUnitStatus = "queued"
	WorkUnitStatusInFlight WorkUnitStatus = "in_flight"
	WorkUnitStatusDone     WorkUnitStatus = "done"
	WorkUnitStatusFailed   WorkUnitStatus = "failed"
)

func (e *WorkUnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkUnitStatus(s)
	case string:
		*e = WorkUnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkUnitStatus: %T", src)
	}
	return nil
}

type NullWorkUnitStatus struct {
	WorkUnitStatus WorkUnitStatus `json:"work_unit_status"`
	Valid          bool           `json:"valid"` // Valid is true if WorkUnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkUnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkUnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkUnitStatus), nil
}

type Agent struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DisplayName  string             `json:"display_name"`
	Harness      string             `json:"harness"`
	BaseUrl      string             `json:"base_url"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Role         pgtype.Text        `json:"role"`
	SystemPrompt pgtype.Text        `json:"system_prompt"`
	Persona      []byte             `json:"persona"`
	Visible      bool               `json:"visible"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
}

type AgentGrant struct {
	ID         pgtype.UUID        `json:"id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	Scope      string             `json:"scope"`
	GrantedAt  pgtype.Timestamptz `json:"granted_at"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
}

type AgentMail struct {
	ID          int64              `json:"id"`
	SenderID    pgtype.UUID        `json:"sender_id"`
	RecipientID pgtype.UUID        `json:"recipient_id"`
	Subject     string             `json:"subject"`
	Body        string             `json:"body"`
	Priority    MailPriority       `json:"priority"`
	Status      MailStatus         `json:"status"`
	ReplyToID   pgtype.Int8        `json:"reply_to_id"`
	Metadata    []byte             `json:"metadata"`
	ContentType string             `json:"content_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppInstance struct {
	ID            pgtype.UUID        `json:"id"`
	Harness       string             `json:"harness"`
	SessionID     string             `json:"session_id"`
	Host          string             `json:"host"`
	Pid           pgtype.Int4        `json:"pid"`
	Label         string             `json:"label"`
	HealthUrl     string             `json:"health_url"`
	Branch        pgtype.Text        `json:"branch"`
	Sha           pgtype.Text        `json:"sha"`
	Cwd           pgtype.Text        `json:"cwd"`
	Tenant        string             `json:"tenant"`
	Status        string             `json:"status"`
	LastProbedAt  pgtype.Timestamptz `json:"last_probed_at"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
}

type Artifact struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Type        string             `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	FilePath    pgtype.Text        `json:"file_path"`
	MimeType    pgtype.Text        `json:"mime_type"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}

type ControlState struct {
	ID             bool               `json:"id"`
	Mode           ControlMode        `json:"mode"`
	CadenceSeconds int32              `json:"cadence_seconds"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Title     pgtype.Text        `json:"title"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Summary   pgtype.Text        `json:"summary"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type Delegation struct {
	ID             pgtype.UUID        `json:"id"`
	ParentAgentID  pgtype.UUID        `json:"parent_agent_id"`
	ChildAgentName string             `json:"child_agent_name"`
	TaskGoal       string             `json:"task_goal"`
	Status         string             `json:"status"`
	ResultSummary  pgtype.Text        `json:"result_summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Metadata       []byte             `json:"metadata"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
}

type Finding struct {
	ID          int64              `json:"id"`
	Ts          pgtype.Timestamptz `json:"ts"`
	PrRef       string             `json:"pr_ref"`
	WpRef       string             `json:"wp_ref"`
	Gate        int32              `json:"gate"`
	AuthorAgent string             `json:"author_agent"`
	Model       string             `json:"model"`
	Severity    string             `json:"severity"`
	Class       string             `json:"class"`
	RootCause   pgtype.Text        `json:"root_cause"`
	Summary     pgtype.Text        `json:"summary"`
}

type Goal struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Progress    pgtype.Float4      `json:"progress"`
	TargetDate  pgtype.Date        `json:"target_date"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}

type HostLiveness struct {
	ID        int64              `json:"id"`
	Host      string             `json:"host"`
	Pid       int32              `json:"pid"`
	SessionID string             `json:"session_id"`
	Harness   string             `json:"harness"`
	Cwd       string             `json:"cwd"`
	Tenant    string             `json:"tenant"`
	Alive     bool               `json:"alive"`
	SeenAt    pgtype.Timestamptz `json:"seen_at"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type IngestKey struct {
	ID        int64              `json:"id"`
	KeyHash   string             `json:"key_hash"`
	Tenant    string             `json:"tenant"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type MemoryIndex struct {
	ID          pgtype.UUID        `json:"id"`
	FilePath    string             `json:"file_path"`
	Title       pgtype.Text        `json:"title"`
	Content     pgtype.Text        `json:"content"`
	Tags        []string           `json:"tags"`
	LastIndexed pgtype.Timestamptz `json:"last_indexed"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
}

type PipelineItem struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Content   pgtype.Text        `json:"content"`
	Metadata  []byte             `json:"metadata"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Tenant      string             `json:"tenant"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Tracker     string             `json:"tracker"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	RepoUrl     pgtype.Text        `json:"repo_url"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}

type Resource struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Kind      string             `json:"kind"`
	Label     string             `json:"label"`
	Provider  string             `json:"provider"`
	IsSecret  bool               `json:"is_secret"`
	EncValue  []byte             `json:"enc_value"`
	EncConfig []byte             `json:"enc_config"`
	Config    []byte             `json:"config"`
	Last4     string             `json:"last4"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type RunLog struct {
	ID        int64              `json:"id"`
	Ts        pgtype.Timestamptz `json:"ts"`
	EventType string             `json:"event_type"`
	PrRef     string             `json:"pr_ref"`
	WpRef     string             `json:"wp_ref"`
	Summary   pgtype.Text        `json:"summary"`
	Payload   []byte             `json:"payload"`
}

type Skill struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Content     string             `json:"content"`
	Triggers    []string           `json:"triggers"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}

type Task struct {
	ID           pgtype.UUID        `json:"id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	Priority     pgtype.Int4        `json:"priority"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
}

type TrackerItem struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ExternalRef  string             `json:"external_ref"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	ItemType     string             `json:"item_type"`
	CanonicalUrl pgtype.Text        `json:"canonical_url"`
	Payload      []byte             `json:"payload"`
	Tenant       string             `json:"tenant"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Login       string             `json:"login"`
	DisplayName string             `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	SchemaVersion string             `json:"schema_version"`
	Harness       string             `json:"harness"`
	SessionID     string             `json:"session_id"`
	Host          string             `json:"host"`
	Pid           pgtype.Int4        `json:"pid"`
	Kind          string             `json:"kind"`
	Status        pgtype.Text        `json:"status"`
	LivenessMode  pgtype.Text        `json:"liveness_mode"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Tenant        string             `json:"tenant"`
	ExternalRef   pgtype.Text        `json:"external_ref"`
	Branch        pgtype.Text        `json:"branch"`
	Sha           pgtype.Text        `json:"sha"`
	Cwd           pgtype.Text        `json:"cwd"`
	Title         pgtype.Text        `json:"title"`
	CostUsd       pgtype.Numeric     `json:"cost_usd"`
	Payload       []byte             `json:"payload"`
	Ts            pgtype.Timestamptz `json:"ts"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
}

type WorkUnit struct {
	ID          int64              `json:"id"`
	WpRef       string             `json:"wp_ref"`
	Status      WorkUnitStatus     `json:"status"`
	Payload     []byte             `json:"payload"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Workflow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Steps       []byte             `json:"steps"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}

type WorkflowRun struct {
	ID          pgtype.UUID        `json:"id"`
	WorkflowID  pgtype.UUID        `json:"workflow_id"`
	Status      pgtype.Text        `json:"status"`
	CurrentStep pgtype.Int4        `json:"current_step"`
	Result      []byte             `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
}
