// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DisplayName  string             `json:"display_name"`
	Harness      string             `json:"harness"`
	BaseUrl      string             `json:"base_url"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Role         pgtype.Text        `json:"role"`
	SystemPrompt pgtype.Text        `json:"system_prompt"`
	Persona      []byte             `json:"persona"`
	Visible      bool               `json:"visible"`
}

type Artifact struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Type        string             `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	FilePath    pgtype.Text        `json:"file_path"`
	MimeType    pgtype.Text        `json:"mime_type"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Title     pgtype.Text        `json:"title"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Summary   pgtype.Text        `json:"summary"`
}

type Delegation struct {
	ID             pgtype.UUID        `json:"id"`
	ParentAgentID  pgtype.UUID        `json:"parent_agent_id"`
	ChildAgentName string             `json:"child_agent_name"`
	TaskGoal       string             `json:"task_goal"`
	Status         string             `json:"status"`
	ResultSummary  pgtype.Text        `json:"result_summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Metadata       []byte             `json:"metadata"`
}

type Goal struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Progress    pgtype.Float4      `json:"progress"`
	TargetDate  pgtype.Date        `json:"target_date"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IngestKey struct {
	ID        int64              `json:"id"`
	KeyHash   string             `json:"key_hash"`
	Tenant    string             `json:"tenant"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type MemoryIndex struct {
	ID          pgtype.UUID        `json:"id"`
	FilePath    string             `json:"file_path"`
	Title       pgtype.Text        `json:"title"`
	Content     pgtype.Text        `json:"content"`
	Tags        []string           `json:"tags"`
	LastIndexed pgtype.Timestamptz `json:"last_indexed"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PipelineItem struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Content   pgtype.Text        `json:"content"`
	Metadata  []byte             `json:"metadata"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Tenant      string             `json:"tenant"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Tracker     string             `json:"tracker"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	RepoUrl     pgtype.Text        `json:"repo_url"`
}

type Skill struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Content     string             `json:"content"`
	Triggers    []string           `json:"triggers"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID           pgtype.UUID        `json:"id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	Priority     pgtype.Int4        `json:"priority"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
}

type TrackerItem struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ExternalRef  string             `json:"external_ref"`
	Title        string             `json:"title"`
	Status       string             `json:"status"`
	ItemType     string             `json:"item_type"`
	CanonicalUrl pgtype.Text        `json:"canonical_url"`
	Payload      []byte             `json:"payload"`
	Tenant       string             `json:"tenant"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WorkEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	SchemaVersion string             `json:"schema_version"`
	Harness       string             `json:"harness"`
	SessionID     string             `json:"session_id"`
	Host          string             `json:"host"`
	Pid           pgtype.Int4        `json:"pid"`
	Kind          string             `json:"kind"`
	Status        pgtype.Text        `json:"status"`
	LivenessMode  pgtype.Text        `json:"liveness_mode"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Tenant        string             `json:"tenant"`
	ExternalRef   pgtype.Text        `json:"external_ref"`
	Branch        pgtype.Text        `json:"branch"`
	Sha           pgtype.Text        `json:"sha"`
	Cwd           pgtype.Text        `json:"cwd"`
	Title         pgtype.Text        `json:"title"`
	CostUsd       pgtype.Numeric     `json:"cost_usd"`
	Payload       []byte             `json:"payload"`
	Ts            pgtype.Timestamptz `json:"ts"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
}

type Workflow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Steps       []byte             `json:"steps"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowRun struct {
	ID          pgtype.UUID        `json:"id"`
	WorkflowID  pgtype.UUID        `json:"workflow_id"`
	Status      pgtype.Text        `json:"status"`
	CurrentStep pgtype.Int4        `json:"current_step"`
	Result      []byte             `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
