// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Harness     string             `json:"harness"`
	BaseUrl     string             `json:"base_url"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Artifact struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Type        string             `json:"type"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	FilePath    pgtype.Text        `json:"file_path"`
	MimeType    pgtype.Text        `json:"mime_type"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Title     pgtype.Text        `json:"title"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Goal struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Progress    pgtype.Float4      `json:"progress"`
	TargetDate  pgtype.Date        `json:"target_date"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MemoryIndex struct {
	ID          pgtype.UUID        `json:"id"`
	FilePath    string             `json:"file_path"`
	Title       pgtype.Text        `json:"title"`
	Content     pgtype.Text        `json:"content"`
	Tags        []string           `json:"tags"`
	LastIndexed pgtype.Timestamptz `json:"last_indexed"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PipelineItem struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Content   pgtype.Text        `json:"content"`
	Metadata  []byte             `json:"metadata"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Priority    pgtype.Int4        `json:"priority"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
