// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestrator.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextWorkUnit = `-- name: ClaimNextWorkUnit :one
UPDATE work_units SET status = 'in_flight', claimed_at = NOW()
WHERE id = (
    SELECT id FROM work_units
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
) RETURNING id, wp_ref, status, payload, claimed_at, completed_at, error, created_at
`

func (q *Queries) ClaimNextWorkUnit(ctx context.Context) (WorkUnit, error) {
	row := q.db.QueryRow(ctx, claimNextWorkUnit)
	var i WorkUnit
	err := row.Scan(
		&i.ID,
		&i.WpRef,
		&i.Status,
		&i.Payload,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const completeWorkUnit = `-- name: CompleteWorkUnit :one
UPDATE work_units SET status = 'done', completed_at = NOW()
WHERE id = $1 AND status = 'in_flight' RETURNING id, wp_ref, status, payload, claimed_at, completed_at, error, created_at
`

func (q *Queries) CompleteWorkUnit(ctx context.Context, id int64) (WorkUnit, error) {
	row := q.db.QueryRow(ctx, completeWorkUnit, id)
	var i WorkUnit
	err := row.Scan(
		&i.ID,
		&i.WpRef,
		&i.Status,
		&i.Payload,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const countWorkUnitsByStatus = `-- name: CountWorkUnitsByStatus :many
SELECT status, COUNT(*)::bigint AS count FROM work_units GROUP BY status
`

type CountWorkUnitsByStatusRow struct {
	Status WorkUnitStatus `json:"status"`
	Count  int64          `json:"count"`
}

func (q *Queries) CountWorkUnitsByStatus(ctx context.Context) ([]CountWorkUnitsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countWorkUnitsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountWorkUnitsByStatusRow
	for rows.Next() {
		var i CountWorkUnitsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueWorkUnit = `-- name: EnqueueWorkUnit :one
INSERT INTO work_units (wp_ref, payload) VALUES ($1, $2) RETURNING id, wp_ref, status, payload, claimed_at, completed_at, error, created_at
`

type EnqueueWorkUnitParams struct {
	WpRef   string `json:"wp_ref"`
	Payload []byte `json:"payload"`
}

func (q *Queries) EnqueueWorkUnit(ctx context.Context, arg EnqueueWorkUnitParams) (WorkUnit, error) {
	row := q.db.QueryRow(ctx, enqueueWorkUnit, arg.WpRef, arg.Payload)
	var i WorkUnit
	err := row.Scan(
		&i.ID,
		&i.WpRef,
		&i.Status,
		&i.Payload,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const failWorkUnit = `-- name: FailWorkUnit :one
UPDATE work_units SET status = 'failed', error = $2, completed_at = NOW()
WHERE id = $1 AND status = 'in_flight' RETURNING id, wp_ref, status, payload, claimed_at, completed_at, error, created_at
`

type FailWorkUnitParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailWorkUnit(ctx context.Context, arg FailWorkUnitParams) (WorkUnit, error) {
	row := q.db.QueryRow(ctx, failWorkUnit, arg.ID, arg.Error)
	var i WorkUnit
	err := row.Scan(
		&i.ID,
		&i.WpRef,
		&i.Status,
		&i.Payload,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getControlState = `-- name: GetControlState :one
SELECT id, mode, cadence_seconds, updated_at FROM control_state
`

func (q *Queries) GetControlState(ctx context.Context) (ControlState, error) {
	row := q.db.QueryRow(ctx, getControlState)
	var i ControlState
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.CadenceSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrchestratorWorkUnits = `-- name: ListOrchestratorWorkUnits :many
SELECT id, wp_ref, status, payload, claimed_at, completed_at, error, created_at FROM work_units ORDER BY created_at
`

func (q *Queries) ListOrchestratorWorkUnits(ctx context.Context) ([]WorkUnit, error) {
	rows, err := q.db.Query(ctx, listOrchestratorWorkUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkUnit
	for rows.Next() {
		var i WorkUnit
		if err := rows.Scan(
			&i.ID,
			&i.WpRef,
			&i.Status,
			&i.Payload,
			&i.ClaimedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkUnitsByStatus = `-- name: ListWorkUnitsByStatus :many
SELECT id, wp_ref, status, payload, claimed_at, completed_at, error, created_at FROM work_units WHERE status = $1::work_unit_status ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListWorkUnitsByStatusParams struct {
	Column1 WorkUnitStatus `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) ListWorkUnitsByStatus(ctx context.Context, arg ListWorkUnitsByStatusParams) ([]WorkUnit, error) {
	rows, err := q.db.Query(ctx, listWorkUnitsByStatus, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkUnit
	for rows.Next() {
		var i WorkUnit
		if err := rows.Scan(
			&i.ID,
			&i.WpRef,
			&i.Status,
			&i.Payload,
			&i.ClaimedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueWorkUnit = `-- name: RequeueWorkUnit :one
UPDATE work_units SET status = 'queued', claimed_at = NULL, completed_at = NULL, error = NULL
WHERE id = $1 AND status = 'failed' RETURNING id, wp_ref, status, payload, claimed_at, completed_at, error, created_at
`

func (q *Queries) RequeueWorkUnit(ctx context.Context, id int64) (WorkUnit, error) {
	row := q.db.QueryRow(ctx, requeueWorkUnit, id)
	var i WorkUnit
	err := row.Scan(
		&i.ID,
		&i.WpRef,
		&i.Status,
		&i.Payload,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const setControlMode = `-- name: SetControlMode :one
UPDATE control_state SET mode = $1, updated_at = NOW() RETURNING id, mode, cadence_seconds, updated_at
`

func (q *Queries) SetControlMode(ctx context.Context, mode ControlMode) (ControlState, error) {
	row := q.db.QueryRow(ctx, setControlMode, mode)
	var i ControlState
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.CadenceSeconds,
		&i.UpdatedAt,
	)
	return i, err
}
