// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipelineItem = `-- name: CreatePipelineItem :one
INSERT INTO pipeline_items (type, title, status, content, metadata, agent_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, title, status, content, metadata, agent_id, created_at, updated_at, owner_id
`

type CreatePipelineItemParams struct {
	Type     string      `json:"type"`
	Title    string      `json:"title"`
	Status   string      `json:"status"`
	Content  pgtype.Text `json:"content"`
	Metadata []byte      `json:"metadata"`
	AgentID  pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreatePipelineItem(ctx context.Context, arg CreatePipelineItemParams) (PipelineItem, error) {
	row := q.db.QueryRow(ctx, createPipelineItem,
		arg.Type,
		arg.Title,
		arg.Status,
		arg.Content,
		arg.Metadata,
		arg.AgentID,
	)
	var i PipelineItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.Content,
		&i.Metadata,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deletePipelineItem = `-- name: DeletePipelineItem :exec
DELETE FROM pipeline_items WHERE id = $1
`

func (q *Queries) DeletePipelineItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePipelineItem, id)
	return err
}

const getPipelineItem = `-- name: GetPipelineItem :one
SELECT id, type, title, status, content, metadata, agent_id, created_at, updated_at, owner_id FROM pipeline_items WHERE id = $1
`

func (q *Queries) GetPipelineItem(ctx context.Context, id pgtype.UUID) (PipelineItem, error) {
	row := q.db.QueryRow(ctx, getPipelineItem, id)
	var i PipelineItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.Content,
		&i.Metadata,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listPipelineItems = `-- name: ListPipelineItems :many
SELECT id, type, title, status, content, metadata, agent_id, created_at, updated_at, owner_id FROM pipeline_items
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR type = $2)
ORDER BY created_at DESC
`

type ListPipelineItemsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) ListPipelineItems(ctx context.Context, arg ListPipelineItemsParams) ([]PipelineItem, error) {
	rows, err := q.db.Query(ctx, listPipelineItems, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineItem
	for rows.Next() {
		var i PipelineItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Status,
			&i.Content,
			&i.Metadata,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipelineItem = `-- name: UpdatePipelineItem :one
UPDATE pipeline_items SET title = $2, status = $3, content = $4, metadata = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, type, title, status, content, metadata, agent_id, created_at, updated_at, owner_id
`

type UpdatePipelineItemParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Status   string      `json:"status"`
	Content  pgtype.Text `json:"content"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdatePipelineItem(ctx context.Context, arg UpdatePipelineItemParams) (PipelineItem, error) {
	row := q.db.QueryRow(ctx, updatePipelineItem,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Content,
		arg.Metadata,
	)
	var i PipelineItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Status,
		&i.Content,
		&i.Metadata,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
