// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, tenant, tracker, external_ref, repo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type CreateProjectParams struct {
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Tenant      string      `json:"tenant"`
	Tracker     string      `json:"tracker"`
	ExternalRef pgtype.Text `json:"external_ref"`
	RepoUrl     pgtype.Text `json:"repo_url"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.Tenant,
		arg.Tracker,
		arg.ExternalRef,
		arg.RepoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const ensureProjectBySlug = `-- name: EnsureProjectBySlug :one
INSERT INTO projects (slug, name, tenant)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET updated_at = NOW()
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type EnsureProjectBySlugParams struct {
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	Tenant string `json:"tenant"`
}

// Idempotent resolution used by the ingest project resolver (contract §1).
func (q *Queries) EnsureProjectBySlug(ctx context.Context, arg EnsureProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, ensureProjectBySlug, arg.Slug, arg.Name, arg.Tenant)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tenant,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tracker,
			&i.ExternalRef,
			&i.RepoUrl,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectTracker = `-- name: UpdateProjectTracker :one
UPDATE projects SET tracker = $2, external_ref = $3, repo_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type UpdateProjectTrackerParams struct {
	ID          pgtype.UUID `json:"id"`
	Tracker     string      `json:"tracker"`
	ExternalRef pgtype.Text `json:"external_ref"`
	RepoUrl     pgtype.Text `json:"repo_url"`
}

func (q *Queries) UpdateProjectTracker(ctx context.Context, arg UpdateProjectTrackerParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectTracker,
		arg.ID,
		arg.Tracker,
		arg.ExternalRef,
		arg.RepoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}
