// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, slug, name, tenant, tracker, external_ref, repo_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type CreateProjectParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Tenant      string      `json:"tenant"`
	Tracker     string      `json:"tracker"`
	ExternalRef pgtype.Text `json:"external_ref"`
	RepoUrl     pgtype.Text `json:"repo_url"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Slug,
		arg.Name,
		arg.Tenant,
		arg.Tracker,
		arg.ExternalRef,
		arg.RepoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const ensureProjectBySlug = `-- name: EnsureProjectBySlug :one
INSERT INTO projects (owner_id, slug, name, tenant)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE SET updated_at = NOW()
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type EnsureProjectBySlugParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Slug    string      `json:"slug"`
	Name    string      `json:"name"`
	Tenant  string      `json:"tenant"`
}

// Idempotent resolution used by the ingest project resolver (contract §1).
func (q *Queries) EnsureProjectBySlug(ctx context.Context, arg EnsureProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, ensureProjectBySlug,
		arg.OwnerID,
		arg.Slug,
		arg.Name,
		arg.Tenant,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects WHERE id = $1 AND owner_id = $2
`

type GetProjectParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects WHERE slug = $1 AND owner_id = $2
`

type GetProjectBySlugParams struct {
	Slug    string      `json:"slug"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.Slug, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id FROM projects WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tenant,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tracker,
			&i.ExternalRef,
			&i.RepoUrl,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, tracker = $3, external_ref = $4, repo_url = $5, updated_at = NOW()
WHERE id = $1 AND owner_id = $6
RETURNING id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url, owner_id
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Tracker     string      `json:"tracker"`
	ExternalRef pgtype.Text `json:"external_ref"`
	RepoUrl     pgtype.Text `json:"repo_url"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

// Updates all mutable project fields: name, tracker, external_ref, repo_url.
// (Renamed from UpdateProjectTracker once name became mutable so the query
// name reflects what it actually persists — previously name was silently
// dropped because it wasn't in the SET clause.)
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Tracker,
		arg.ExternalRef,
		arg.RepoUrl,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tenant,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tracker,
		&i.ExternalRef,
		&i.RepoUrl,
		&i.OwnerID,
	)
	return i, err
}
