// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanStaleDelegations(ctx context.Context) error
	CountArtifacts(ctx context.Context, dollar_1 string) (int64, error)
	CountDelegations(ctx context.Context, arg CountDelegationsParams) (int64, error)
	CountSubtasks(ctx context.Context, parentTaskID pgtype.UUID) (int64, error)
	CountTrackerItemsByProject(ctx context.Context, arg CountTrackerItemsByProjectParams) (int64, error)
	CountTrackerItemsByTenant(ctx context.Context, tenant string) (int64, error)
	// Consistent with ListWorkUnits grouping (same key) so pagination Total matches.
	CountWorkUnits(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePipelineItem(ctx context.Context, arg CreatePipelineItemParams) (PipelineItem, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Task, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error)
	DeleteAgent(ctx context.Context, id pgtype.UUID) error
	DeleteArtifact(ctx context.Context, id pgtype.UUID) error
	DeleteGoal(ctx context.Context, id pgtype.UUID) error
	DeleteLastExchange(ctx context.Context, conversationID pgtype.UUID) (int64, error)
	DeleteMemory(ctx context.Context, filePath string) error
	DeleteMessage(ctx context.Context, id pgtype.UUID) error
	DeleteMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) (int64, error)
	DeletePipelineItem(ctx context.Context, id pgtype.UUID) error
	DeleteSkill(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteWorkflow(ctx context.Context, id pgtype.UUID) error
	EnsureAgent(ctx context.Context, arg EnsureAgentParams) (Agent, error)
	// Idempotent resolution used by the ingest project resolver (contract §1).
	EnsureProjectBySlug(ctx context.Context, arg EnsureProjectBySlugParams) (Project, error)
	GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error)
	GetArtifactByPath(ctx context.Context, filePath pgtype.Text) (Artifact, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error)
	GetDelegation(ctx context.Context, id pgtype.UUID) (Delegation, error)
	GetGoal(ctx context.Context, id pgtype.UUID) (Goal, error)
	GetLastUserMessage(ctx context.Context, conversationID pgtype.UUID) (Message, error)
	GetLatestWorkflowRun(ctx context.Context, workflowID pgtype.UUID) (WorkflowRun, error)
	GetMemoryByPath(ctx context.Context, filePath string) (MemoryIndex, error)
	GetPipelineItem(ctx context.Context, id pgtype.UUID) (PipelineItem, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetSkill(ctx context.Context, id pgtype.UUID) (Skill, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	GetTrackerItem(ctx context.Context, arg GetTrackerItemParams) (TrackerItem, error)
	// Returns all projects configured with a given tracker type, scoped to a tenant.
	GetTrackerProjects(ctx context.Context, arg GetTrackerProjectsParams) ([]Project, error)
	GetWorkEventByEventID(ctx context.Context, eventID pgtype.UUID) (WorkEvent, error)
	GetWorkEventsBySession(ctx context.Context, arg GetWorkEventsBySessionParams) ([]WorkEvent, error)
	// All events in one group (drill-down). Matches the same 5-part key as ListWorkUnits,
	// NULL-safe so the uncorrelated buckets match rows with NULL key parts.
	GetWorkUnitEvents(ctx context.Context, arg GetWorkUnitEventsParams) ([]WorkEvent, error)
	GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error)
	GetWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error)
	// Upsert by event_id: inserts new row, on conflict does nothing and returns nothing (pgx.ErrNoRows).
	InsertWorkEvent(ctx context.Context, arg InsertWorkEventParams) (WorkEvent, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error)
	ListConversations(ctx context.Context, dollar_1 pgtype.UUID) ([]Conversation, error)
	ListDelegations(ctx context.Context, arg ListDelegationsParams) ([]Delegation, error)
	ListGoals(ctx context.Context) ([]Goal, error)
	ListMemoryIndex(ctx context.Context) ([]MemoryIndex, error)
	ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
	ListPipelineItems(ctx context.Context, arg ListPipelineItemsParams) ([]PipelineItem, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSkillSummaries(ctx context.Context) ([]ListSkillSummariesRow, error)
	ListSkills(ctx context.Context) ([]Skill, error)
	ListSkillsByAgent(ctx context.Context, agentID pgtype.UUID) ([]Skill, error)
	ListSubtasks(ctx context.Context, parentTaskID pgtype.UUID) ([]Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTrackerItemsByProject(ctx context.Context, arg ListTrackerItemsByProjectParams) ([]TrackerItem, error)
	ListTrackerItemsByTenant(ctx context.Context, arg ListTrackerItemsByTenantParams) ([]TrackerItem, error)
	ListVisibleAgents(ctx context.Context) ([]Agent, error)
	// WP-B correlation engine. Groups work_events into work_units by the correlation key.
	// Per contract §7 the key is (project_id, external_ref, branch, sha); we ALSO group by
	// `tenant` so two tenants emitting the same external_ref with a NULL project_id are never
	// merged into one unit (ADR-002 D6 — employer tenants never co-mingle).
	// Events sharing no code/tracker anchor are surfaced as `correlated=false` units, grouped
	// by their (tenant, project) context — NEVER dropped (ADR-001 F3). The no-drop invariant:
	// SUM(event_count) over all units == COUNT(*) of work_events.
	ListWorkUnits(ctx context.Context, arg ListWorkUnitsParams) ([]ListWorkUnitsRow, error)
	ListWorkflowRuns(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowRun, error)
	ListWorkflows(ctx context.Context) ([]Workflow, error)
	SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]MemoryIndex, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) (Agent, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error)
	UpdateConversationMetadata(ctx context.Context, arg UpdateConversationMetadataParams) (Conversation, error)
	UpdateConversationSummary(ctx context.Context, arg UpdateConversationSummaryParams) (Conversation, error)
	UpdateDelegation(ctx context.Context, arg UpdateDelegationParams) (Delegation, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdatePipelineItem(ctx context.Context, arg UpdatePipelineItemParams) (PipelineItem, error)
	UpdateProjectTracker(ctx context.Context, arg UpdateProjectTrackerParams) (Project, error)
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
	UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (WorkflowRun, error)
	UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (MemoryIndex, error)
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error)
	// Upsert a tracker item on (project_id, external_ref). Updates title/status/type/url/payload and bumps synced_at.
	UpsertTrackerItem(ctx context.Context, arg UpsertTrackerItemParams) (TrackerItem, error)
}

var _ Querier = (*Queries)(nil)
