// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountArtifacts(ctx context.Context, dollar_1 string) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePipelineItem(ctx context.Context, arg CreatePipelineItemParams) (PipelineItem, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteAgent(ctx context.Context, id pgtype.UUID) error
	DeleteArtifact(ctx context.Context, id pgtype.UUID) error
	DeleteGoal(ctx context.Context, id pgtype.UUID) error
	DeleteMemory(ctx context.Context, filePath string) error
	DeletePipelineItem(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error)
	GetGoal(ctx context.Context, id pgtype.UUID) (Goal, error)
	GetMemoryByPath(ctx context.Context, filePath string) (MemoryIndex, error)
	GetPipelineItem(ctx context.Context, id pgtype.UUID) (PipelineItem, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error)
	ListConversations(ctx context.Context, dollar_1 pgtype.UUID) ([]Conversation, error)
	ListGoals(ctx context.Context) ([]Goal, error)
	ListMemoryIndex(ctx context.Context) ([]MemoryIndex, error)
	ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
	ListPipelineItems(ctx context.Context, arg ListPipelineItemsParams) ([]PipelineItem, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]MemoryIndex, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdatePipelineItem(ctx context.Context, arg UpdatePipelineItemParams) (PipelineItem, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (MemoryIndex, error)
}

var _ Querier = (*Queries)(nil)
