// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Aggregates USAGE (tokens_used + turns) and cost_usd from work_events, grouped by
	// the requested dimension (agent/harness, project, tenant, or day). Pure read over
	// existing work_events.
	//
	// Provider-aware spend (Option A): token/turn usage is ALWAYS meaningful and is the
	// primary metric. cost_usd is OPTIONAL — subscription accounts never report it, so we
	// must NOT drop sessions that lack a dollar figure (the old `WHERE cost_usd IS NOT NULL`
	// + `HAVING SUM(cost_usd) > 0` did exactly that, hiding all subscription usage). cost_usd
	// is summed as a nullable value: NULL when no session in the group reported a cost.
	//
	// Per contract §5, cost_usd / telemetry is cumulative for the session and "latest
	// received_at wins"; we dedupe to the latest event per (harness, session_id) before
	// rolling up. tokens_used and turns come from payload->telemetry (non-core fields).
	// Tenant-scoped: @tenant = '' returns all tenants; otherwise scopes to one (UNCHANGED —
	// this isolation predicate is load-bearing and must not regress).
	// Include any group with real activity: tokens OR turns OR a dollar cost. This keeps
	// subscription agents (cost NULL, tokens > 0) visible while still excluding empty noise.
	// Usage-first ordering: most tokens, then turns, then dollars (nulls last).
	AggregateSpend(ctx context.Context, arg AggregateSpendParams) ([]AggregateSpendRow, error)
	AppendFinding(ctx context.Context, arg AppendFindingParams) (Finding, error)
	AppendRunLog(ctx context.Context, arg AppendRunLogParams) (RunLog, error)
	ClaimNextWorkUnit(ctx context.Context) (WorkUnit, error)
	CleanStaleDelegations(ctx context.Context) error
	CompleteWorkUnit(ctx context.Context, id int64) (WorkUnit, error)
	// Count active (non-revoked) keys for a tenant.
	CountActiveIngestKeys(ctx context.Context, arg CountActiveIngestKeysParams) (int64, error)
	// Counts app instances matching the tenant filter (for pagination total).
	CountAppInstances(ctx context.Context, arg CountAppInstancesParams) (int64, error)
	CountArtifacts(ctx context.Context, arg CountArtifactsParams) (int64, error)
	CountArtifactsByProject(ctx context.Context, arg CountArtifactsByProjectParams) (int64, error)
	CountDelegations(ctx context.Context, arg CountDelegationsParams) (int64, error)
	// Returns total count of distinct (harness, session_id) matching the tenant filter.
	CountEmitterHealthSessions(ctx context.Context, tenant string) (int64, error)
	CountFindings(ctx context.Context) (int64, error)
	CountFindingsByClass(ctx context.Context, class string) (int64, error)
	CountFindingsBySeverity(ctx context.Context, severity string) (int64, error)
	CountFindingsByWpRef(ctx context.Context, wpRef string) (int64, error)
	// Counts liveness records matching the tenant filter.
	CountHostLiveness(ctx context.Context, arg CountHostLivenessParams) (int64, error)
	CountMailbox(ctx context.Context, arg CountMailboxParams) (int64, error)
	// Workspace surface (issue #134): how many notes belong to a project.
	CountMemoryByProject(ctx context.Context, arg CountMemoryByProjectParams) (int64, error)
	CountRunLog(ctx context.Context) (int64, error)
	CountRunLogByWpRef(ctx context.Context, wpRef string) (int64, error)
	// Counts distinct (harness, session_id) pairs that have at least one
	// session lifecycle event for a given tenant.
	CountSessions(ctx context.Context, tenant string) (int64, error)
	// Returns the total count of active groups matching the given filters, without
	// LIMIT/OFFSET. "Active" mirrors AggregateSpend's HAVING (tokens OR turns OR cost),
	// so the count stays consistent with the rows actually returned.
	CountSpendGroups(ctx context.Context, arg CountSpendGroupsParams) (int64, error)
	CountSubtasks(ctx context.Context, arg CountSubtasksParams) (int64, error)
	CountTrackerItemsByProject(ctx context.Context, arg CountTrackerItemsByProjectParams) (int64, error)
	CountTrackerItemsByTenant(ctx context.Context, arg CountTrackerItemsByTenantParams) (int64, error)
	CountUnread(ctx context.Context, recipientID pgtype.UUID) (int64, error)
	// Consistent with ListWorkUnits grouping (same key + same tenant filter) so Total matches.
	CountWorkUnits(ctx context.Context, tenant string) (int64, error)
	CountWorkUnitsByStatus(ctx context.Context) ([]CountWorkUnitsByStatusRow, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	// Inserts a new app instance. Returns the created row.
	CreateAppInstance(ctx context.Context, arg CreateAppInstanceParams) (AppInstance, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	// Insert a new ingest key (hashed). The raw key is never stored — callers
	// must hash before calling this.
	CreateIngestKey(ctx context.Context, arg CreateIngestKeyParams) (IngestKey, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePipelineItem(ctx context.Context, arg CreatePipelineItemParams) (PipelineItem, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Task, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserKey(ctx context.Context, arg CreateUserKeyParams) (UserKey, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error)
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) error
	// Deletes an app instance by ID.
	DeleteAppInstance(ctx context.Context, arg DeleteAppInstanceParams) error
	DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteGoal(ctx context.Context, arg DeleteGoalParams) error
	DeleteLastExchange(ctx context.Context, arg DeleteLastExchangeParams) (int64, error)
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessagesByConversation(ctx context.Context, arg DeleteMessagesByConversationParams) (int64, error)
	DeletePipelineItem(ctx context.Context, arg DeletePipelineItemParams) error
	DeleteResource(ctx context.Context, arg DeleteResourceParams) error
	DeleteSkill(ctx context.Context, arg DeleteSkillParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error
	EnqueueWorkUnit(ctx context.Context, arg EnqueueWorkUnitParams) (WorkUnit, error)
	EnsureAgent(ctx context.Context, arg EnsureAgentParams) (Agent, error)
	// Idempotent resolution used by the ingest project resolver (contract §1).
	EnsureProjectBySlug(ctx context.Context, arg EnsureProjectBySlugParams) (Project, error)
	ExpireMail(ctx context.Context) error
	ExpireMailByID(ctx context.Context, arg ExpireMailByIDParams) (AgentMail, error)
	FailWorkUnit(ctx context.Context, arg FailWorkUnitParams) (WorkUnit, error)
	GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error)
	GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (Agent, error)
	GetAgentByNameAndOwner(ctx context.Context, arg GetAgentByNameAndOwnerParams) (Agent, error)
	// Fetches a single app instance by ID.
	GetAppInstance(ctx context.Context, arg GetAppInstanceParams) (AppInstance, error)
	GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error)
	GetArtifactByPath(ctx context.Context, arg GetArtifactByPathParams) (Artifact, error)
	// Returns the latest host-liveness alive status for a bounded session.
	// Joins the session's (host, pid) from work_events (kind=session.start) with
	// host_liveness to get the latest alive report. COALESCE(NULL, false) means
	// "no reporter proof → not alive" (contract §4: never running without proof).
	//
	// Derivation rule (consumed by deriveBoundedStatus in session_liveness.go):
	//   alive=true  → session is running (positive proof from host reporter)
	//   alive=false → session is stale (process killed/crashed)
	//   no row      → no reporter proof → stale (NEVER running without proof)
	//
	// NOTE: seen_at freshness — the reporter only POSTs alive=true on first-seen
	// and cwd-change. Long-running processes do NOT re-POST alive=true. The
	// derivation must account for this (see session_liveness.go BoundedMaxAge
	// backstop and the proposed seen_at TTL in the PR-body wiring diff).
	GetBoundedSessionHostLiveness(ctx context.Context, arg GetBoundedSessionHostLivenessParams) (bool, error)
	GetControlState(ctx context.Context) (ControlState, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	GetDelegation(ctx context.Context, arg GetDelegationParams) (Delegation, error)
	// Returns per-session liveness state derived from work_events.
	// Pure read — no migration needed (WP-M).
	// Computes liveness as a PURE FUNCTION of (persisted events, server clock now).
	// Contract §4: running requires positive proof (heartbeat within timeout);
	// absence of proof ⇒ stale, never "running" (ADR-001 F10 / ADR-003 D3).
	// Terminal (session.end) is absorbing: once seen, later non-terminal events are
	// ignored for liveness purposes.
	// @stale_window: supervised sessions with no heartbeat in this window are stale.
	//   Default = 5 minutes (contract §4).
	// @tenant: required — scopes to one tenant (handler rejects empty).
	GetEmitterHealth(ctx context.Context, arg GetEmitterHealthParams) ([]GetEmitterHealthRow, error)
	GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error)
	// Fetches a single host-liveness row by (host, pid).
	// Optional tenant filter: returns rows only for matching tenant (or all if empty).
	GetHostLiveness(ctx context.Context, arg GetHostLivenessParams) (HostLiveness, error)
	// Look up a (non-revoked) ingest key by its SHA-256 hash.
	// Returns NULL (pgx.ErrNoRows) if not found or revoked.
	GetIngestKeyByHash(ctx context.Context, arg GetIngestKeyByHashParams) (IngestKey, error)
	GetLastUserMessage(ctx context.Context, arg GetLastUserMessageParams) (Message, error)
	// Returns the latest session.start or session.heartbeat received_at for a
	// supervised (harness, session_id, tenant). Used to compute supervised liveness.
	// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
	// Returns pgx.ErrNoRows if no start/heartbeat exists.
	GetLatestHeartbeat(ctx context.Context, arg GetLatestHeartbeatParams) (pgtype.Timestamptz, error)
	GetLatestWorkflowRun(ctx context.Context, arg GetLatestWorkflowRunParams) (WorkflowRun, error)
	GetMail(ctx context.Context, arg GetMailParams) (AgentMail, error)
	GetMailThread(ctx context.Context, arg GetMailThreadParams) ([]AgentMail, error)
	GetMailbox(ctx context.Context, arg GetMailboxParams) ([]AgentMail, error)
	GetMemoryByPath(ctx context.Context, arg GetMemoryByPathParams) (MemoryIndex, error)
	GetPipelineItem(ctx context.Context, arg GetPipelineItemParams) (PipelineItem, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetResource(ctx context.Context, arg GetResourceParams) (Resource, error)
	GetResourceBySlug(ctx context.Context, arg GetResourceBySlugParams) (Resource, error)
	// Returns the received_at of the first session.start event for a session.
	// Used to compute bounded_max_age (6h backstop from contract §4).
	// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
	// Returns pgx.ErrNoRows if no session.start exists.
	GetSessionStartTime(ctx context.Context, arg GetSessionStartTimeParams) (pgtype.Timestamptz, error)
	// Returns the latest session.end event for a (harness, session_id, tenant), if any.
	// Used to check if a session is in a terminal (absorbing) state.
	// Tenant-scoped to prevent cross-tenant absorption (ADR-002).
	// Returns pgx.ErrNoRows if no terminal event exists.
	GetSessionTerminalEvent(ctx context.Context, arg GetSessionTerminalEventParams) (GetSessionTerminalEventRow, error)
	GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTrackerItem(ctx context.Context, arg GetTrackerItemParams) (TrackerItem, error)
	// Returns all projects configured with a given tracker type, scoped to a tenant.
	GetTrackerProjects(ctx context.Context, arg GetTrackerProjectsParams) ([]Project, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetUserKey(ctx context.Context, userID pgtype.UUID) (UserKey, error)
	GetWorkEventByEventID(ctx context.Context, arg GetWorkEventByEventIDParams) (WorkEvent, error)
	GetWorkEventsBySession(ctx context.Context, arg GetWorkEventsBySessionParams) ([]WorkEvent, error)
	// All events in one group (drill-down). Matches the same 5-part key as ListWorkUnits,
	// NULL-safe so the uncorrelated buckets match rows with NULL key parts.
	GetWorkUnitEvents(ctx context.Context, arg GetWorkUnitEventsParams) ([]WorkEvent, error)
	GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error)
	GetWorkflowRun(ctx context.Context, arg GetWorkflowRunParams) (WorkflowRun, error)
	GrantResource(ctx context.Context, arg GrantResourceParams) (AgentGrant, error)
	// Upsert by event_id: inserts new row, on conflict does nothing and returns nothing (pgx.ErrNoRows).
	InsertWorkEvent(ctx context.Context, arg InsertWorkEventParams) (WorkEvent, error)
	// Agent session liveness queries for the fleet monitor (WP-J, F10).
	// NOTE: The SessionLivenessService (session_liveness.go) uses inline raw SQL
	// rather than these sqlc-generated queries. This file exists as the declared
	// contract for the liveness queries. If the service SQL drifts from these
	// declarations, the tests in session_liveness_test.go will catch it. A future
	// refactor may wire these generated queries directly.
	// Returns all sessions for a tenant that have a session.start event, ordered by
	// the latest event received_at descending. The caller derives liveness from
	// the returned events in application code (contract §4: pure function of events + clock).
	// Tenant is required (never empty — ADR-002).
	ListActiveSessions(ctx context.Context, tenant string) ([]ListActiveSessionsRow, error)
	ListAgents(ctx context.Context, ownerID pgtype.UUID) ([]Agent, error)
	// Workspace scoping (issue #134): agents assigned to a given project.
	ListAgentsByProject(ctx context.Context, arg ListAgentsByProjectParams) ([]Agent, error)
	ListAllGrants(ctx context.Context, ownerID pgtype.UUID) ([]AgentGrant, error)
	// Lists app instances scoped to a tenant. Returns all if tenant is empty.
	// Supports pagination with limit/offset.
	// Orders by last_probed_at DESC NULLS LAST (never-probed instances at end).
	ListAppInstances(ctx context.Context, arg ListAppInstancesParams) ([]AppInstance, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error)
	// Workspace scoping (issue #134): artifacts scoped to a project, with the
	// same optional type filter as ListArtifacts.
	ListArtifactsByProject(ctx context.Context, arg ListArtifactsByProjectParams) ([]Artifact, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error)
	ListDelegations(ctx context.Context, arg ListDelegationsParams) ([]Delegation, error)
	ListFindings(ctx context.Context, arg ListFindingsParams) ([]Finding, error)
	ListFindingsByClass(ctx context.Context, arg ListFindingsByClassParams) ([]Finding, error)
	ListFindingsBySeverity(ctx context.Context, arg ListFindingsBySeverityParams) ([]Finding, error)
	ListFindingsByWpRef(ctx context.Context, arg ListFindingsByWpRefParams) ([]Finding, error)
	ListGoals(ctx context.Context, ownerID pgtype.UUID) ([]Goal, error)
	ListGrantsForAgent(ctx context.Context, arg ListGrantsForAgentParams) ([]AgentGrant, error)
	ListGrantsForResource(ctx context.Context, arg ListGrantsForResourceParams) ([]AgentGrant, error)
	// Lists all liveness records for a tenant, ordered by seen_at DESC.
	// Returns all if tenant is empty.
	ListHostLiveness(ctx context.Context, arg ListHostLivenessParams) ([]HostLiveness, error)
	// List all (including revoked) keys for a tenant, newest first.
	ListIngestKeysByTenant(ctx context.Context, arg ListIngestKeysByTenantParams) ([]IngestKey, error)
	ListLegacyResources(ctx context.Context) ([]Resource, error)
	ListMemoryIndex(ctx context.Context, ownerID pgtype.UUID) ([]MemoryIndex, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListOrchestratorWorkUnits(ctx context.Context) ([]WorkUnit, error)
	ListPipelineItems(ctx context.Context, arg ListPipelineItemsParams) ([]PipelineItem, error)
	ListProjects(ctx context.Context, ownerID pgtype.UUID) ([]Project, error)
	ListResources(ctx context.Context, ownerID pgtype.UUID) ([]Resource, error)
	ListResourcesByKind(ctx context.Context, arg ListResourcesByKindParams) ([]Resource, error)
	// ListResourcesForAgent filters ONLY by agent_id and intentionally does NOT
	// re-check owner_id. Cross-owner isolation is enforced one layer up, at
	// GRANT CREATION: GrantAgentResource (internal/api/resources.go) validates that
	// BOTH the agent and the resource belong to the calling owner via the
	// owner-scoped GetAgent/GetResource lookups before it inserts an agent_grants
	// row, so every grant is inherently intra-owner.
	//
	// DO NOT reuse this query from any code path that creates grants without that
	// ownership check — doing so would silently leak another owner's (possibly
	// secret) resources. Regression guard: TestGrantCrossOwnerIsolation.
	ListResourcesForAgent(ctx context.Context, agentID pgtype.UUID) ([]Resource, error)
	ListRunLog(ctx context.Context, arg ListRunLogParams) ([]RunLog, error)
	ListRunLogByWpRef(ctx context.Context, arg ListRunLogByWpRefParams) ([]RunLog, error)
	ListSkillSummaries(ctx context.Context, ownerID pgtype.UUID) ([]ListSkillSummariesRow, error)
	ListSkills(ctx context.Context, ownerID pgtype.UUID) ([]Skill, error)
	ListSkillsByAgent(ctx context.Context, arg ListSkillsByAgentParams) ([]Skill, error)
	ListSubtasks(ctx context.Context, arg ListSubtasksParams) ([]Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTrackerItemsByProject(ctx context.Context, arg ListTrackerItemsByProjectParams) ([]TrackerItem, error)
	ListTrackerItemsByTenant(ctx context.Context, arg ListTrackerItemsByTenantParams) ([]TrackerItem, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVisibleAgents(ctx context.Context, ownerID pgtype.UUID) ([]Agent, error)
	// WP-B correlation engine. Groups work_events into work_units by the correlation key.
	// Per contract §7 the key is (project_id, external_ref, branch, sha); we ALSO group by
	// `tenant` so two tenants emitting the same external_ref with a NULL project_id are never
	// merged into one unit (ADR-002 D6 — employer tenants never co-mingle).
	// Events sharing no code/tracker anchor are surfaced as `correlated=false` units, grouped
	// by their (tenant, project) context — NEVER dropped (ADR-001 F3). The no-drop invariant:
	// SUM(event_count) over all units == COUNT(*) of work_events.
	// Two-level aggregation so liveness is honest (review findings B1/B2/B5):
	//   1. session_state: collapse each (key, harness, session_id) to ONE session, taking its
	//      latest LIFECYCLE status (only session.start/heartbeat/end drive status — a later
	//      artifact.created/note with status='unknown' must NOT mask a terminal session: B1).
	//   2. session_live: derive per-session liveness from the SERVER clock NOW() (contract §4:
	//      received_at is the only liveness clock — so we compute it here, not on the browser).
	//   3. outer: aggregate sessions into the unit with precedence failed>running>stale>done (B2),
	//      and SUM per-session cost (cumulative per session) for a correct unit total (B5).
	// Optional tenant filter (B3): @tenant = '' returns all tenants; otherwise scopes to one.
	ListWorkUnits(ctx context.Context, arg ListWorkUnitsParams) ([]ListWorkUnitsRow, error)
	ListWorkUnitsByStatus(ctx context.Context, arg ListWorkUnitsByStatusParams) ([]WorkUnit, error)
	ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error)
	ListWorkflows(ctx context.Context, ownerID pgtype.UUID) ([]Workflow, error)
	// Called when a server.stopped work-event arrives (contract §4).
	// Sets status to 'down' — this is a definitive signal, not a probe.
	MarkInstanceDownByServerStopped(ctx context.Context, arg MarkInstanceDownByServerStoppedParams) error
	MarkMailRead(ctx context.Context, arg MarkMailReadParams) (AgentMail, error)
	RecurringFindings(ctx context.Context, dollar_1 interface{}) ([]RecurringFindingsRow, error)
	RenameAgent(ctx context.Context, arg RenameAgentParams) (Agent, error)
	RequeueWorkUnit(ctx context.Context, id int64) (WorkUnit, error)
	// Revoke an ingest key by setting revoked_at to now.
	RevokeIngestKey(ctx context.Context, arg RevokeIngestKeyParams) error
	RevokeResource(ctx context.Context, arg RevokeResourceParams) error
	SearchMemory(ctx context.Context, arg SearchMemoryParams) ([]MemoryIndex, error)
	// agent_mail.sql — agent-to-agent messaging (WP-101, issue #112).
	// All inbox reads are scoped by recipient_id (an agent only ever sees its own
	// mail). Expired mail (expires_at in the past) is excluded from inbox listings
	// and unread counts so the absence is observable without a background sweeper.
	SendMail(ctx context.Context, arg SendMailParams) (AgentMail, error)
	// Assign (or clear, when project_id is NULL) an agent to a workspace.
	SetAgentProject(ctx context.Context, arg SetAgentProjectParams) (Agent, error)
	// Assign (or clear) an artifact to a workspace.
	SetArtifactProject(ctx context.Context, arg SetArtifactProjectParams) error
	SetControlMode(ctx context.Context, mode ControlMode) (ControlState, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) (Agent, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error)
	UpdateConversationMetadata(ctx context.Context, arg UpdateConversationMetadataParams) (Conversation, error)
	UpdateConversationSummary(ctx context.Context, arg UpdateConversationSummaryParams) (Conversation, error)
	UpdateDelegation(ctx context.Context, arg UpdateDelegationParams) (Delegation, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	// Marks an instance as 'down' (from server.stopped event or probe failure).
	UpdateInstanceDown(ctx context.Context, arg UpdateInstanceDownParams) error
	// Updates the status and last_probed_at of an instance after a probe.
	// This is the ONLY way status changes — never set from a work-event.
	UpdateInstanceProbeStatus(ctx context.Context, arg UpdateInstanceProbeStatusParams) error
	UpdatePipelineItem(ctx context.Context, arg UpdatePipelineItemParams) (PipelineItem, error)
	UpdateProjectTracker(ctx context.Context, arg UpdateProjectTrackerParams) (Project, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateResourceEncryption(ctx context.Context, arg UpdateResourceEncryptionParams) error
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
	UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (WorkflowRun, error)
	// Upserts an instance keyed on (host, health_url, tenant).
	// Used by server.started work-event auto-creation: if the same host+url+tenant
	// already exists, updates its session_id, branch, sha, pid, and label.
	// Does NOT change status — only a real probe updates status (anti-fake-status rule).
	UpsertAppInstanceByHostURL(ctx context.Context, arg UpsertAppInstanceByHostURLParams) (AppInstance, error)
	// Called when a server.started work-event arrives (contract §4).
	// Creates the instance if not known, or updates session/branch/sha.
	// Status is set to 'unknown' only on creation (needs a real probe to go 'up').
	UpsertAppInstanceOnServerStarted(ctx context.Context, arg UpsertAppInstanceOnServerStartedParams) (AppInstance, error)
	// Upserts a host-liveness report keyed on (host, pid).
	// This is the liveness *feed* (WP-N); session-state derivation is a
	// separate consumer concern (WP-J / follow-on WPs).
	UpsertHostLiveness(ctx context.Context, arg UpsertHostLivenessParams) (HostLiveness, error)
	UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (MemoryIndex, error)
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error)
	// Upsert a tracker item on (project_id, external_ref). Updates title/status/type/url/payload and bumps synced_at.
	UpsertTrackerItem(ctx context.Context, arg UpsertTrackerItemParams) (TrackerItem, error)
}

var _ Querier = (*Queries)(nil)
