// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (owner_id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, enc_key_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
`

type CreateResourceParams struct {
	OwnerID       pgtype.UUID `json:"owner_id"`
	Slug          string      `json:"slug"`
	Kind          string      `json:"kind"`
	Label         string      `json:"label"`
	Provider      string      `json:"provider"`
	IsSecret      bool        `json:"is_secret"`
	EncValue      []byte      `json:"enc_value"`
	EncConfig     []byte      `json:"enc_config"`
	Config        []byte      `json:"config"`
	Last4         string      `json:"last4"`
	Status        string      `json:"status"`
	EncKeyVersion int32       `json:"enc_key_version"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.OwnerID,
		arg.Slug,
		arg.Kind,
		arg.Label,
		arg.Provider,
		arg.IsSecret,
		arg.EncValue,
		arg.EncConfig,
		arg.Config,
		arg.Last4,
		arg.Status,
		arg.EncKeyVersion,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.EncKeyVersion,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1 AND owner_id = $2
`

type DeleteResourceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.Exec(ctx, deleteResource, arg.ID, arg.OwnerID)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
FROM resources WHERE id = $1 AND owner_id = $2
`

type GetResourceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ID, arg.OwnerID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.EncKeyVersion,
	)
	return i, err
}

const getResourceBySlug = `-- name: GetResourceBySlug :one
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
FROM resources WHERE slug = $1 AND owner_id = $2
`

type GetResourceBySlugParams struct {
	Slug    string      `json:"slug"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetResourceBySlug(ctx context.Context, arg GetResourceBySlugParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceBySlug, arg.Slug, arg.OwnerID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.EncKeyVersion,
	)
	return i, err
}

const grantResource = `-- name: GrantResource :one
INSERT INTO agent_grants (owner_id, agent_id, resource_id, scope)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, resource_id, scope) DO UPDATE SET granted_at = agent_grants.granted_at
RETURNING id, agent_id, resource_id, scope, granted_at, owner_id
`

type GrantResourceParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Scope      string      `json:"scope"`
}

func (q *Queries) GrantResource(ctx context.Context, arg GrantResourceParams) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, grantResource,
		arg.OwnerID,
		arg.AgentID,
		arg.ResourceID,
		arg.Scope,
	)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ResourceID,
		&i.Scope,
		&i.GrantedAt,
		&i.OwnerID,
	)
	return i, err
}

const listAllGrants = `-- name: ListAllGrants :many
SELECT id, agent_id, resource_id, scope, granted_at, owner_id FROM agent_grants WHERE owner_id = $1
`

func (q *Queries) ListAllGrants(ctx context.Context, ownerID pgtype.UUID) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listAllGrants, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForAgent = `-- name: ListGrantsForAgent :many
SELECT g.id, g.agent_id, g.resource_id, g.scope, g.granted_at, g.owner_id
FROM agent_grants g WHERE g.agent_id = $1 AND g.owner_id = $2
`

type ListGrantsForAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListGrantsForAgent(ctx context.Context, arg ListGrantsForAgentParams) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsForAgent, arg.AgentID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForResource = `-- name: ListGrantsForResource :many
SELECT g.id, g.agent_id, g.resource_id, g.scope, g.granted_at, g.owner_id
FROM agent_grants g WHERE g.resource_id = $1 AND g.owner_id = $2
`

type ListGrantsForResourceParams struct {
	ResourceID pgtype.UUID `json:"resource_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListGrantsForResource(ctx context.Context, arg ListGrantsForResourceParams) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsForResource, arg.ResourceID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
FROM resources WHERE owner_id = $1 ORDER BY kind, label, slug
`

func (q *Queries) ListResources(ctx context.Context, ownerID pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.EncKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByKind = `-- name: ListResourcesByKind :many
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
FROM resources WHERE kind = $1 AND owner_id = $2 ORDER BY label, slug
`

type ListResourcesByKindParams struct {
	Kind    string      `json:"kind"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListResourcesByKind(ctx context.Context, arg ListResourcesByKindParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByKind, arg.Kind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.EncKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesForAgent = `-- name: ListResourcesForAgent :many
SELECT r.id, r.slug, r.kind, r.label, r.provider, r.is_secret, r.enc_value, r.enc_config, r.config, r.last4, r.status, r.created_at, r.updated_at, r.owner_id, r.enc_key_version
FROM resources r
JOIN agent_grants g ON g.resource_id = r.id
WHERE g.agent_id = $1 AND r.owner_id = $2
ORDER BY r.kind, r.label
`

type ListResourcesForAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListResourcesForAgent(ctx context.Context, arg ListResourcesForAgentParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesForAgent, arg.AgentID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.EncKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeResource = `-- name: RevokeResource :exec
DELETE FROM agent_grants WHERE agent_id = $1 AND resource_id = $2 AND owner_id = $3
`

type RevokeResourceParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	ResourceID pgtype.UUID `json:"resource_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

func (q *Queries) RevokeResource(ctx context.Context, arg RevokeResourceParams) error {
	_, err := q.db.Exec(ctx, revokeResource, arg.AgentID, arg.ResourceID, arg.OwnerID)
	return err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET label = $2, provider = $3, is_secret = $4, enc_value = $5, enc_config = $6, config = $7, last4 = $8, status = $9, enc_key_version = $10, updated_at = NOW()
WHERE id = $1 AND owner_id = $11
RETURNING id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
`

type UpdateResourceParams struct {
	ID            pgtype.UUID `json:"id"`
	Label         string      `json:"label"`
	Provider      string      `json:"provider"`
	IsSecret      bool        `json:"is_secret"`
	EncValue      []byte      `json:"enc_value"`
	EncConfig     []byte      `json:"enc_config"`
	Config        []byte      `json:"config"`
	Last4         string      `json:"last4"`
	Status        string      `json:"status"`
	EncKeyVersion int32       `json:"enc_key_version"`
	OwnerID       pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Label,
		arg.Provider,
		arg.IsSecret,
		arg.EncValue,
		arg.EncConfig,
		arg.Config,
		arg.Last4,
		arg.Status,
		arg.EncKeyVersion,
		arg.OwnerID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.EncKeyVersion,
	)
	return i, err
}
