// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
`

type CreateResourceParams struct {
	Slug      string `json:"slug"`
	Kind      string `json:"kind"`
	Label     string `json:"label"`
	Provider  string `json:"provider"`
	IsSecret  bool   `json:"is_secret"`
	EncValue  []byte `json:"enc_value"`
	EncConfig []byte `json:"enc_config"`
	Config    []byte `json:"config"`
	Last4     string `json:"last4"`
	Status    string `json:"status"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.Slug,
		arg.Kind,
		arg.Label,
		arg.Provider,
		arg.IsSecret,
		arg.EncValue,
		arg.EncConfig,
		arg.Config,
		arg.Last4,
		arg.Status,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
FROM resources WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id pgtype.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const getResourceBySlug = `-- name: GetResourceBySlug :one
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
FROM resources WHERE slug = $1
`

func (q *Queries) GetResourceBySlug(ctx context.Context, slug string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceBySlug, slug)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const grantResource = `-- name: GrantResource :one
INSERT INTO agent_grants (agent_id, resource_id, scope)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, resource_id, scope) DO UPDATE SET granted_at = agent_grants.granted_at
RETURNING id, agent_id, resource_id, scope, granted_at, owner_id
`

type GrantResourceParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Scope      string      `json:"scope"`
}

func (q *Queries) GrantResource(ctx context.Context, arg GrantResourceParams) (AgentGrant, error) {
	row := q.db.QueryRow(ctx, grantResource, arg.AgentID, arg.ResourceID, arg.Scope)
	var i AgentGrant
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ResourceID,
		&i.Scope,
		&i.GrantedAt,
		&i.OwnerID,
	)
	return i, err
}

const listAllGrants = `-- name: ListAllGrants :many
SELECT id, agent_id, resource_id, scope, granted_at, owner_id FROM agent_grants
`

func (q *Queries) ListAllGrants(ctx context.Context) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listAllGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForAgent = `-- name: ListGrantsForAgent :many
SELECT g.id, g.agent_id, g.resource_id, g.scope, g.granted_at, g.owner_id
FROM agent_grants g WHERE g.agent_id = $1
`

func (q *Queries) ListGrantsForAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForResource = `-- name: ListGrantsForResource :many
SELECT g.id, g.agent_id, g.resource_id, g.scope, g.granted_at, g.owner_id
FROM agent_grants g WHERE g.resource_id = $1
`

func (q *Queries) ListGrantsForResource(ctx context.Context, resourceID pgtype.UUID) ([]AgentGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGrant
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ResourceID,
			&i.Scope,
			&i.GrantedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
FROM resources ORDER BY kind, label, slug
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByKind = `-- name: ListResourcesByKind :many
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
FROM resources WHERE kind = $1 ORDER BY label, slug
`

func (q *Queries) ListResourcesByKind(ctx context.Context, kind string) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesForAgent = `-- name: ListResourcesForAgent :many
SELECT r.id, r.slug, r.kind, r.label, r.provider, r.is_secret, r.enc_value, r.enc_config, r.config, r.last4, r.status, r.created_at, r.updated_at, r.owner_id
FROM resources r
JOIN agent_grants g ON g.resource_id = r.id
WHERE g.agent_id = $1
ORDER BY r.kind, r.label
`

func (q *Queries) ListResourcesForAgent(ctx context.Context, agentID pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeResource = `-- name: RevokeResource :exec
DELETE FROM agent_grants WHERE agent_id = $1 AND resource_id = $2
`

type RevokeResourceParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	ResourceID pgtype.UUID `json:"resource_id"`
}

func (q *Queries) RevokeResource(ctx context.Context, arg RevokeResourceParams) error {
	_, err := q.db.Exec(ctx, revokeResource, arg.AgentID, arg.ResourceID)
	return err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET label = $2, provider = $3, is_secret = $4, enc_value = $5, enc_config = $6, config = $7, last4 = $8, status = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id
`

type UpdateResourceParams struct {
	ID        pgtype.UUID `json:"id"`
	Label     string      `json:"label"`
	Provider  string      `json:"provider"`
	IsSecret  bool        `json:"is_secret"`
	EncValue  []byte      `json:"enc_value"`
	EncConfig []byte      `json:"enc_config"`
	Config    []byte      `json:"config"`
	Last4     string      `json:"last4"`
	Status    string      `json:"status"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Label,
		arg.Provider,
		arg.IsSecret,
		arg.EncValue,
		arg.EncConfig,
		arg.Config,
		arg.Last4,
		arg.Status,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Provider,
		&i.IsSecret,
		&i.EncValue,
		&i.EncConfig,
		&i.Config,
		&i.Last4,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
