// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (owner_id, name, description, category, content, triggers, agent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id
`

type CreateSkillParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1 AND owner_id = $2
`

type DeleteSkillParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.OwnerID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id FROM skills WHERE id = $1 AND owner_id = $2
`

type GetSkillParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.OwnerID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listSkillSummaries = `-- name: ListSkillSummaries :many
SELECT id, name, description, category, triggers, agent_id, created_at, updated_at
FROM skills
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListSkillSummariesRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Triggers    []string           `json:"triggers"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSkillSummaries(ctx context.Context, ownerID pgtype.UUID) ([]ListSkillSummariesRow, error) {
	rows, err := q.db.Query(ctx, listSkillSummaries, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillSummariesRow
	for rows.Next() {
		var i ListSkillSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Triggers,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id FROM skills
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSkills(ctx context.Context, ownerID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Triggers,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByAgent = `-- name: ListSkillsByAgent :many
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id FROM skills
WHERE agent_id = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListSkillsByAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListSkillsByAgent(ctx context.Context, arg ListSkillsByAgentParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByAgent, arg.AgentID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Triggers,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET name = $2, description = $3, category = $4, content = $5, triggers = $6, agent_id = $7, updated_at = NOW()
WHERE id = $1 AND owner_id = $8
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id
`

type UpdateSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
		arg.OwnerID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (owner_id, name, description, category, content, triggers, agent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    content = EXCLUDED.content,
    triggers = EXCLUDED.triggers,
    updated_at = NOW()
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at, owner_id
`

type UpsertSkillParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
