// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name, description, category, content, triggers, agent_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at
`

type CreateSkillParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at FROM skills WHERE id = $1
`

func (q *Queries) GetSkill(ctx context.Context, id pgtype.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at FROM skills
ORDER BY created_at DESC
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Triggers,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByAgent = `-- name: ListSkillsByAgent :many
SELECT id, name, description, category, content, triggers, agent_id, created_at, updated_at FROM skills
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSkillsByAgent(ctx context.Context, agentID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Content,
			&i.Triggers,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET name = $2, description = $3, category = $4, content = $5, triggers = $6, agent_id = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at
`

type UpdateSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (name, description, category, content, triggers, agent_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    content = EXCLUDED.content,
    triggers = EXCLUDED.triggers,
    updated_at = NOW()
RETURNING id, name, description, category, content, triggers, agent_id, created_at, updated_at
`

type UpsertSkillParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
	Content     string      `json:"content"`
	Triggers    []string    `json:"triggers"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Content,
		arg.Triggers,
		arg.AgentID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Content,
		&i.Triggers,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
