// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spend.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateSpend = `-- name: AggregateSpend :many
WITH latest_per_session AS (
    SELECT DISTINCT ON (harness, session_id)
        harness,
        COALESCE(project_id::text, '') AS project_key,
        tenant,
        ts::date                       AS day,
        cost_usd,
        (payload->'telemetry'->>'turns')::int AS turns,
        external_ref
    FROM work_events
    WHERE cost_usd IS NOT NULL
      AND ($4::text = '' OR tenant = $4::text)
      AND ($5::text = '' OR external_ref = $5::text)
    ORDER BY harness, session_id, received_at DESC
),
spend_source AS (
    SELECT
        harness,
        project_key,
        tenant,
        day,
        cost_usd,
        turns
    FROM latest_per_session
)
SELECT
    CASE $1
        WHEN 'agent'  THEN harness
        WHEN 'project' THEN project_key
        WHEN 'tenant' THEN tenant
        WHEN 'day'    THEN day::text
        ELSE harness   -- default fallback = agent
    END::text  AS dimension_key,
    SUM(cost_usd)::numeric          AS total_cost_usd,
    COUNT(*)::bigint                AS event_count,
    COALESCE(SUM(COALESCE(turns, 0))::bigint, 0)::bigint AS total_turns,
    COUNT(*) OVER()::bigint          AS total_groups
FROM spend_source
GROUP BY
    CASE $1
        WHEN 'agent'  THEN harness
        WHEN 'project' THEN project_key
        WHEN 'tenant' THEN tenant
        WHEN 'day'    THEN day::text
        ELSE harness
    END::text
HAVING SUM(cost_usd) > 0
ORDER BY SUM(cost_usd) DESC
LIMIT $3 OFFSET $2
`

type AggregateSpendParams struct {
	GroupBy     string `json:"group_by"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
	Tenant      string `json:"tenant"`
	ExternalRef string `json:"external_ref"`
}

type AggregateSpendRow struct {
	DimensionKey string         `json:"dimension_key"`
	TotalCostUsd pgtype.Numeric `json:"total_cost_usd"`
	EventCount   int64          `json:"event_count"`
	TotalTurns   int64          `json:"total_turns"`
	TotalGroups  int64          `json:"total_groups"`
}

// Aggregates cost_usd + num_turns (from telemetry) from work_events, grouped by the
// requested dimension (agent/harness, project, tenant, or day). Pure read over
// existing work_events — no migration needed (WP-K).
// Cost has ONE source of truth: top-level cost_usd (contract §5).
// Turns are counted from payload->telemetry->turns (non-null only).
// Tenant-scoped: @tenant = ” returns all tenants; otherwise scopes to one.
// external_ref filter: @external_ref = ” returns all; otherwise scopes to one.
// Per the work-event contract (§5, lines 213-215), cost_usd is "cumulative for the
// session; non-decreasing" and "latest received_at wins." We dedupe to the latest
// event per (harness, session_id) before rolling up, so a session that emits
// start=$0.05 then end=$0.07 contributes $0.07, not $0.12.
func (q *Queries) AggregateSpend(ctx context.Context, arg AggregateSpendParams) ([]AggregateSpendRow, error) {
	rows, err := q.db.Query(ctx, aggregateSpend,
		arg.GroupBy,
		arg.Off,
		arg.Lim,
		arg.Tenant,
		arg.ExternalRef,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateSpendRow
	for rows.Next() {
		var i AggregateSpendRow
		if err := rows.Scan(
			&i.DimensionKey,
			&i.TotalCostUsd,
			&i.EventCount,
			&i.TotalTurns,
			&i.TotalGroups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpendGroups = `-- name: CountSpendGroups :one
WITH latest_per_session AS (
    SELECT DISTINCT ON (harness, session_id)
        harness,
        COALESCE(project_id::text, '') AS project_key,
        tenant,
        ts::date                       AS day,
        cost_usd,
        (payload->'telemetry'->>'turns')::int AS turns,
        external_ref
    FROM work_events
    WHERE cost_usd IS NOT NULL
      AND ($2::text = '' OR tenant = $2::text)
      AND ($3::text = '' OR external_ref = $3::text)
    ORDER BY harness, session_id, received_at DESC
),
spend_source AS (
    SELECT
        harness,
        project_key,
        tenant,
        day,
        cost_usd,
        turns
    FROM latest_per_session
)
SELECT COUNT(*)::bigint AS total_groups
FROM (
    SELECT 1
    FROM spend_source
    GROUP BY
        CASE $1
            WHEN 'agent'  THEN harness
            WHEN 'project' THEN project_key
            WHEN 'tenant' THEN tenant
            WHEN 'day'    THEN day::text
            ELSE harness
        END::text
    HAVING SUM(cost_usd) > 0
) AS groups
`

type CountSpendGroupsParams struct {
	GroupBy     string `json:"group_by"`
	Tenant      string `json:"tenant"`
	ExternalRef string `json:"external_ref"`
}

// Returns the total count of non-zero-cost groups matching the given filters,
// without applying LIMIT/OFFSET. Used when the main query returns zero rows
// (offset past end) so Total is still accurate.
func (q *Queries) CountSpendGroups(ctx context.Context, arg CountSpendGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpendGroups, arg.GroupBy, arg.Tenant, arg.ExternalRef)
	var total_groups int64
	err := row.Scan(&total_groups)
	return total_groups, err
}
