// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spend.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateSpend = `-- name: AggregateSpend :many
WITH latest_per_session AS (
    SELECT DISTINCT ON (harness, session_id)
        harness,
        COALESCE(project_id::text, '') AS project_key,
        tenant,
        ts::date                       AS day,
        cost_usd,
        (payload->'telemetry'->>'turns')::int        AS turns,
        (payload->'telemetry'->>'tokens_used')::bigint AS tokens_used,
        external_ref
    FROM work_events
    WHERE ($4::text = '' OR tenant = $4::text)
      AND ($5::text = '' OR external_ref = $5::text)
    ORDER BY harness, session_id, received_at DESC
),
spend_source AS (
    SELECT
        harness,
        project_key,
        tenant,
        day,
        cost_usd,
        turns,
        tokens_used
    FROM latest_per_session
)
SELECT
    CASE $1
        WHEN 'agent'  THEN harness
        WHEN 'project' THEN project_key
        WHEN 'tenant' THEN tenant
        WHEN 'day'    THEN day::text
        ELSE harness   -- default fallback = agent
    END::text  AS dimension_key,
    SUM(cost_usd)::numeric                                AS total_cost_usd,
    COALESCE(SUM(COALESCE(tokens_used, 0)), 0)::bigint    AS total_tokens,
    COALESCE(SUM(COALESCE(turns, 0)), 0)::bigint          AS total_turns,
    COUNT(*)::bigint                                      AS session_count,
    COUNT(*) OVER()::bigint                               AS total_groups
FROM spend_source
GROUP BY
    CASE $1
        WHEN 'agent'  THEN harness
        WHEN 'project' THEN project_key
        WHEN 'tenant' THEN tenant
        WHEN 'day'    THEN day::text
        ELSE harness
    END::text
HAVING COALESCE(SUM(COALESCE(tokens_used, 0)), 0) > 0
    OR COALESCE(SUM(COALESCE(turns, 0)), 0) > 0
    OR COALESCE(SUM(cost_usd), 0) > 0
ORDER BY
    COALESCE(SUM(COALESCE(tokens_used, 0)), 0) DESC,
    COALESCE(SUM(COALESCE(turns, 0)), 0) DESC,
    SUM(cost_usd) DESC NULLS LAST
LIMIT $3 OFFSET $2
`

type AggregateSpendParams struct {
	GroupBy     string `json:"group_by"`
	Off         int32  `json:"off"`
	Lim         int32  `json:"lim"`
	Tenant      string `json:"tenant"`
	ExternalRef string `json:"external_ref"`
}

type AggregateSpendRow struct {
	DimensionKey string         `json:"dimension_key"`
	TotalCostUsd pgtype.Numeric `json:"total_cost_usd"`
	TotalTokens  int64          `json:"total_tokens"`
	TotalTurns   int64          `json:"total_turns"`
	SessionCount int64          `json:"session_count"`
	TotalGroups  int64          `json:"total_groups"`
}

// Aggregates USAGE (tokens_used + turns) and cost_usd from work_events, grouped by
// the requested dimension (agent/harness, project, tenant, or day). Pure read over
// existing work_events.
//
// Provider-aware spend (Option A): token/turn usage is ALWAYS meaningful and is the
// primary metric. cost_usd is OPTIONAL — subscription accounts never report it, so we
// must NOT drop sessions that lack a dollar figure (the old `WHERE cost_usd IS NOT NULL`
// + `HAVING SUM(cost_usd) > 0` did exactly that, hiding all subscription usage). cost_usd
// is summed as a nullable value: NULL when no session in the group reported a cost.
//
// Per contract §5, cost_usd / telemetry is cumulative for the session and "latest
// received_at wins"; we dedupe to the latest event per (harness, session_id) before
// rolling up. tokens_used and turns come from payload->telemetry (non-core fields).
// Tenant-scoped: @tenant = ” returns all tenants; otherwise scopes to one (UNCHANGED —
// this isolation predicate is load-bearing and must not regress).
// Include any group with real activity: tokens OR turns OR a dollar cost. This keeps
// subscription agents (cost NULL, tokens > 0) visible while still excluding empty noise.
// Usage-first ordering: most tokens, then turns, then dollars (nulls last).
func (q *Queries) AggregateSpend(ctx context.Context, arg AggregateSpendParams) ([]AggregateSpendRow, error) {
	rows, err := q.db.Query(ctx, aggregateSpend,
		arg.GroupBy,
		arg.Off,
		arg.Lim,
		arg.Tenant,
		arg.ExternalRef,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateSpendRow
	for rows.Next() {
		var i AggregateSpendRow
		if err := rows.Scan(
			&i.DimensionKey,
			&i.TotalCostUsd,
			&i.TotalTokens,
			&i.TotalTurns,
			&i.SessionCount,
			&i.TotalGroups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpendGroups = `-- name: CountSpendGroups :one
WITH latest_per_session AS (
    SELECT DISTINCT ON (harness, session_id)
        harness,
        COALESCE(project_id::text, '') AS project_key,
        tenant,
        ts::date                       AS day,
        cost_usd,
        (payload->'telemetry'->>'turns')::int        AS turns,
        (payload->'telemetry'->>'tokens_used')::bigint AS tokens_used,
        external_ref
    FROM work_events
    WHERE ($2::text = '' OR tenant = $2::text)
      AND ($3::text = '' OR external_ref = $3::text)
    ORDER BY harness, session_id, received_at DESC
),
spend_source AS (
    SELECT
        harness,
        project_key,
        tenant,
        day,
        cost_usd,
        turns,
        tokens_used
    FROM latest_per_session
)
SELECT COUNT(*)::bigint AS total_groups
FROM (
    SELECT 1
    FROM spend_source
    GROUP BY
        CASE $1
            WHEN 'agent'  THEN harness
            WHEN 'project' THEN project_key
            WHEN 'tenant' THEN tenant
            WHEN 'day'    THEN day::text
            ELSE harness
        END::text
    HAVING COALESCE(SUM(COALESCE(tokens_used, 0)), 0) > 0
        OR COALESCE(SUM(COALESCE(turns, 0)), 0) > 0
        OR COALESCE(SUM(cost_usd), 0) > 0
) AS groups
`

type CountSpendGroupsParams struct {
	GroupBy     string `json:"group_by"`
	Tenant      string `json:"tenant"`
	ExternalRef string `json:"external_ref"`
}

// Returns the total count of active groups matching the given filters, without
// LIMIT/OFFSET. "Active" mirrors AggregateSpend's HAVING (tokens OR turns OR cost),
// so the count stays consistent with the rows actually returned.
func (q *Queries) CountSpendGroups(ctx context.Context, arg CountSpendGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpendGroups, arg.GroupBy, arg.Tenant, arg.ExternalRef)
	var total_groups int64
	err := row.Scan(&total_groups)
	return total_groups, err
}
