// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracker.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTrackerItemsByProject = `-- name: CountTrackerItemsByProject :one
SELECT COUNT(*) FROM tracker_items WHERE project_id = $1 AND tenant = $2
`

type CountTrackerItemsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Tenant    string      `json:"tenant"`
}

func (q *Queries) CountTrackerItemsByProject(ctx context.Context, arg CountTrackerItemsByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackerItemsByProject, arg.ProjectID, arg.Tenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrackerItemsByTenant = `-- name: CountTrackerItemsByTenant :one
SELECT COUNT(*) FROM tracker_items WHERE tenant = $1
`

func (q *Queries) CountTrackerItemsByTenant(ctx context.Context, tenant string) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackerItemsByTenant, tenant)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrackerItem = `-- name: GetTrackerItem :one
SELECT id, project_id, external_ref, title, status, item_type, canonical_url, payload, tenant, synced_at, created_at, updated_at FROM tracker_items
WHERE project_id = $1 AND external_ref = $2
`

type GetTrackerItemParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ExternalRef string      `json:"external_ref"`
}

func (q *Queries) GetTrackerItem(ctx context.Context, arg GetTrackerItemParams) (TrackerItem, error) {
	row := q.db.QueryRow(ctx, getTrackerItem, arg.ProjectID, arg.ExternalRef)
	var i TrackerItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalRef,
		&i.Title,
		&i.Status,
		&i.ItemType,
		&i.CanonicalUrl,
		&i.Payload,
		&i.Tenant,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackerProjects = `-- name: GetTrackerProjects :many
SELECT id, slug, name, tenant, created_at, updated_at, tracker, external_ref, repo_url FROM projects WHERE tracker = $1 AND tenant = $2
`

type GetTrackerProjectsParams struct {
	Tracker string `json:"tracker"`
	Tenant  string `json:"tenant"`
}

// Returns all projects configured with a given tracker type, scoped to a tenant.
func (q *Queries) GetTrackerProjects(ctx context.Context, arg GetTrackerProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, getTrackerProjects, arg.Tracker, arg.Tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tenant,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tracker,
			&i.ExternalRef,
			&i.RepoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackerItemsByProject = `-- name: ListTrackerItemsByProject :many
SELECT id, project_id, external_ref, title, status, item_type, canonical_url, payload, tenant, synced_at, created_at, updated_at FROM tracker_items
WHERE project_id = $1 AND tenant = $2
ORDER BY synced_at DESC
LIMIT $3 OFFSET $4
`

type ListTrackerItemsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Tenant    string      `json:"tenant"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTrackerItemsByProject(ctx context.Context, arg ListTrackerItemsByProjectParams) ([]TrackerItem, error) {
	rows, err := q.db.Query(ctx, listTrackerItemsByProject,
		arg.ProjectID,
		arg.Tenant,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackerItem
	for rows.Next() {
		var i TrackerItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalRef,
			&i.Title,
			&i.Status,
			&i.ItemType,
			&i.CanonicalUrl,
			&i.Payload,
			&i.Tenant,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackerItemsByTenant = `-- name: ListTrackerItemsByTenant :many
SELECT id, project_id, external_ref, title, status, item_type, canonical_url, payload, tenant, synced_at, created_at, updated_at FROM tracker_items
WHERE tenant = $1
ORDER BY synced_at DESC
LIMIT $2 OFFSET $3
`

type ListTrackerItemsByTenantParams struct {
	Tenant string `json:"tenant"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListTrackerItemsByTenant(ctx context.Context, arg ListTrackerItemsByTenantParams) ([]TrackerItem, error) {
	rows, err := q.db.Query(ctx, listTrackerItemsByTenant, arg.Tenant, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackerItem
	for rows.Next() {
		var i TrackerItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalRef,
			&i.Title,
			&i.Status,
			&i.ItemType,
			&i.CanonicalUrl,
			&i.Payload,
			&i.Tenant,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackerItem = `-- name: UpsertTrackerItem :one
INSERT INTO tracker_items (
    project_id, external_ref, title, status, item_type, canonical_url, payload, tenant, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
) ON CONFLICT (project_id, external_ref) DO UPDATE SET
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    item_type = EXCLUDED.item_type,
    canonical_url = EXCLUDED.canonical_url,
    payload = EXCLUDED.payload,
    synced_at = NOW(),
    updated_at = NOW()
RETURNING id, project_id, external_ref, title, status, item_type, canonical_url, payload, tenant, synced_at, created_at, updated_at
`

type UpsertTrackerItemParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ExternalRef  string      `json:"external_ref"`
	Title        string      `json:"title"`
	Status       string      `json:"status"`
	ItemType     string      `json:"item_type"`
	CanonicalUrl pgtype.Text `json:"canonical_url"`
	Payload      []byte      `json:"payload"`
	Tenant       string      `json:"tenant"`
}

// Upsert a tracker item on (project_id, external_ref). Updates title/status/type/url/payload and bumps synced_at.
func (q *Queries) UpsertTrackerItem(ctx context.Context, arg UpsertTrackerItemParams) (TrackerItem, error) {
	row := q.db.QueryRow(ctx, upsertTrackerItem,
		arg.ProjectID,
		arg.ExternalRef,
		arg.Title,
		arg.Status,
		arg.ItemType,
		arg.CanonicalUrl,
		arg.Payload,
		arg.Tenant,
	)
	var i TrackerItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalRef,
		&i.Title,
		&i.Status,
		&i.ItemType,
		&i.CanonicalUrl,
		&i.Payload,
		&i.Tenant,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
