// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserKey = `-- name: CreateUserKey :one
INSERT INTO user_keys (user_id, wrapped_dek, key_version)
VALUES ($1, $2, 1)
ON CONFLICT (user_id) DO NOTHING
RETURNING user_id, wrapped_dek, key_version, created_at, rotated_at
`

type CreateUserKeyParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	WrappedDek []byte      `json:"wrapped_dek"`
}

func (q *Queries) CreateUserKey(ctx context.Context, arg CreateUserKeyParams) (UserKey, error) {
	row := q.db.QueryRow(ctx, createUserKey, arg.UserID, arg.WrappedDek)
	var i UserKey
	err := row.Scan(
		&i.UserID,
		&i.WrappedDek,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getUserKey = `-- name: GetUserKey :one
SELECT user_id, wrapped_dek, key_version, created_at, rotated_at
FROM user_keys WHERE user_id = $1 AND key_version = 1
`

func (q *Queries) GetUserKey(ctx context.Context, userID pgtype.UUID) (UserKey, error) {
	row := q.db.QueryRow(ctx, getUserKey, userID)
	var i UserKey
	err := row.Scan(
		&i.UserID,
		&i.WrappedDek,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const listLegacyResources = `-- name: ListLegacyResources :many
SELECT id, slug, kind, label, provider, is_secret, enc_value, enc_config, config, last4, status, created_at, updated_at, owner_id, enc_key_version
FROM resources WHERE enc_key_version = 0 AND enc_value IS NOT NULL AND length(enc_value) > 0
`

func (q *Queries) ListLegacyResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listLegacyResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Provider,
			&i.IsSecret,
			&i.EncValue,
			&i.EncConfig,
			&i.Config,
			&i.Last4,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.EncKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceEncryption = `-- name: UpdateResourceEncryption :exec
UPDATE resources SET enc_value = $2, enc_key_version = $3, updated_at = NOW() WHERE id = $1
`

type UpdateResourceEncryptionParams struct {
	ID            pgtype.UUID `json:"id"`
	EncValue      []byte      `json:"enc_value"`
	EncKeyVersion int32       `json:"enc_key_version"`
}

func (q *Queries) UpdateResourceEncryption(ctx context.Context, arg UpdateResourceEncryptionParams) error {
	_, err := q.db.Exec(ctx, updateResourceEncryption, arg.ID, arg.EncValue, arg.EncKeyVersion)
	return err
}
