// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (owner_id, name, description, steps, agent_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, steps, agent_id, created_at, updated_at, owner_id
`

type CreateWorkflowParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Steps       []byte      `json:"steps"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Steps,
		arg.AgentID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (owner_id, workflow_id, status, current_step, result)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workflow_id, status, current_step, result, created_at, updated_at, owner_id
`

type CreateWorkflowRunParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	WorkflowID  pgtype.UUID `json:"workflow_id"`
	Status      pgtype.Text `json:"status"`
	CurrentStep pgtype.Int4 `json:"current_step"`
	Result      []byte      `json:"result"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.OwnerID,
		arg.WorkflowID,
		arg.Status,
		arg.CurrentStep,
		arg.Result,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.CurrentStep,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE id = $1 AND owner_id = $2
`

type DeleteWorkflowParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.OwnerID)
	return err
}

const getLatestWorkflowRun = `-- name: GetLatestWorkflowRun :one
SELECT id, workflow_id, status, current_step, result, created_at, updated_at, owner_id FROM workflow_runs
WHERE workflow_id = $1 AND owner_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestWorkflowRunParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetLatestWorkflowRun(ctx context.Context, arg GetLatestWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowRun, arg.WorkflowID, arg.OwnerID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.CurrentStep,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, description, steps, agent_id, created_at, updated_at, owner_id FROM workflows WHERE id = $1 AND owner_id = $2
`

type GetWorkflowParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.OwnerID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, status, current_step, result, created_at, updated_at, owner_id FROM workflow_runs WHERE id = $1 AND owner_id = $2
`

type GetWorkflowRunParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetWorkflowRun(ctx context.Context, arg GetWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, arg.ID, arg.OwnerID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.CurrentStep,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, status, current_step, result, created_at, updated_at, owner_id FROM workflow_runs
WHERE workflow_id = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListWorkflowRunsParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, arg.WorkflowID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.CurrentStep,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, description, steps, agent_id, created_at, updated_at, owner_id FROM workflows
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context, ownerID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Steps,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows SET name = $2, description = $3, steps = $4, agent_id = $5, updated_at = NOW()
WHERE id = $1 AND owner_id = $6
RETURNING id, name, description, steps, agent_id, created_at, updated_at, owner_id
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Steps       []byte      `json:"steps"`
	AgentID     pgtype.UUID `json:"agent_id"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Steps,
		arg.AgentID,
		arg.OwnerID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Steps,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const updateWorkflowRun = `-- name: UpdateWorkflowRun :one
UPDATE workflow_runs SET status = $2, current_step = $3, result = $4, updated_at = NOW()
WHERE id = $1 AND owner_id = $5
RETURNING id, workflow_id, status, current_step, result, created_at, updated_at, owner_id
`

type UpdateWorkflowRunParams struct {
	ID          pgtype.UUID `json:"id"`
	Status      pgtype.Text `json:"status"`
	CurrentStep pgtype.Int4 `json:"current_step"`
	Result      []byte      `json:"result"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRun,
		arg.ID,
		arg.Status,
		arg.CurrentStep,
		arg.Result,
		arg.OwnerID,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.CurrentStep,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
