// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workevents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkEventByEventID = `-- name: GetWorkEventByEventID :one
SELECT id, event_id, schema_version, harness, session_id, host, pid, kind, status, liveness_mode, project_id, tenant, external_ref, branch, sha, cwd, title, cost_usd, payload, ts, received_at FROM work_events WHERE event_id = $1
`

func (q *Queries) GetWorkEventByEventID(ctx context.Context, eventID pgtype.UUID) (WorkEvent, error) {
	row := q.db.QueryRow(ctx, getWorkEventByEventID, eventID)
	var i WorkEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SchemaVersion,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Kind,
		&i.Status,
		&i.LivenessMode,
		&i.ProjectID,
		&i.Tenant,
		&i.ExternalRef,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Title,
		&i.CostUsd,
		&i.Payload,
		&i.Ts,
		&i.ReceivedAt,
	)
	return i, err
}

const getWorkEventsBySession = `-- name: GetWorkEventsBySession :many
SELECT id, event_id, schema_version, harness, session_id, host, pid, kind, status, liveness_mode, project_id, tenant, external_ref, branch, sha, cwd, title, cost_usd, payload, ts, received_at FROM work_events
WHERE harness = $1 AND session_id = $2
ORDER BY received_at DESC
LIMIT $3
`

type GetWorkEventsBySessionParams struct {
	Harness   string `json:"harness"`
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetWorkEventsBySession(ctx context.Context, arg GetWorkEventsBySessionParams) ([]WorkEvent, error) {
	rows, err := q.db.Query(ctx, getWorkEventsBySession, arg.Harness, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkEvent
	for rows.Next() {
		var i WorkEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SchemaVersion,
			&i.Harness,
			&i.SessionID,
			&i.Host,
			&i.Pid,
			&i.Kind,
			&i.Status,
			&i.LivenessMode,
			&i.ProjectID,
			&i.Tenant,
			&i.ExternalRef,
			&i.Branch,
			&i.Sha,
			&i.Cwd,
			&i.Title,
			&i.CostUsd,
			&i.Payload,
			&i.Ts,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWorkEvent = `-- name: InsertWorkEvent :one
INSERT INTO work_events (
    event_id, schema_version, harness, session_id, host, pid,
    kind, status, liveness_mode, project_id, tenant,
    external_ref, branch, sha, cwd, title, cost_usd, payload, ts
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19
) ON CONFLICT (event_id) DO NOTHING
RETURNING id, event_id, schema_version, harness, session_id, host, pid, kind, status, liveness_mode, project_id, tenant, external_ref, branch, sha, cwd, title, cost_usd, payload, ts, received_at
`

type InsertWorkEventParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	SchemaVersion string             `json:"schema_version"`
	Harness       string             `json:"harness"`
	SessionID     string             `json:"session_id"`
	Host          string             `json:"host"`
	Pid           pgtype.Int4        `json:"pid"`
	Kind          string             `json:"kind"`
	Status        pgtype.Text        `json:"status"`
	LivenessMode  pgtype.Text        `json:"liveness_mode"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Tenant        string             `json:"tenant"`
	ExternalRef   pgtype.Text        `json:"external_ref"`
	Branch        pgtype.Text        `json:"branch"`
	Sha           pgtype.Text        `json:"sha"`
	Cwd           pgtype.Text        `json:"cwd"`
	Title         pgtype.Text        `json:"title"`
	CostUsd       pgtype.Numeric     `json:"cost_usd"`
	Payload       []byte             `json:"payload"`
	Ts            pgtype.Timestamptz `json:"ts"`
}

// Upsert by event_id: inserts new row, on conflict does nothing and returns nothing (pgx.ErrNoRows).
func (q *Queries) InsertWorkEvent(ctx context.Context, arg InsertWorkEventParams) (WorkEvent, error) {
	row := q.db.QueryRow(ctx, insertWorkEvent,
		arg.EventID,
		arg.SchemaVersion,
		arg.Harness,
		arg.SessionID,
		arg.Host,
		arg.Pid,
		arg.Kind,
		arg.Status,
		arg.LivenessMode,
		arg.ProjectID,
		arg.Tenant,
		arg.ExternalRef,
		arg.Branch,
		arg.Sha,
		arg.Cwd,
		arg.Title,
		arg.CostUsd,
		arg.Payload,
		arg.Ts,
	)
	var i WorkEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SchemaVersion,
		&i.Harness,
		&i.SessionID,
		&i.Host,
		&i.Pid,
		&i.Kind,
		&i.Status,
		&i.LivenessMode,
		&i.ProjectID,
		&i.Tenant,
		&i.ExternalRef,
		&i.Branch,
		&i.Sha,
		&i.Cwd,
		&i.Title,
		&i.CostUsd,
		&i.Payload,
		&i.Ts,
		&i.ReceivedAt,
	)
	return i, err
}
